### ISSUE TITLE
Build on Travis against multiple R versions

### ISSUE THREAD

**Issue by sckott** [USGS-R/sbtools#101]
https://github.com/metacran/r-builder

Pretty easy to use - I use it on a number of my packages. If not needed, no worries. The builds for each R version run at the same time, so it should only take as long as 1 build takes now. However, it doesn't appear to work with the new travis file setup using `language: r`, etc. if that matters

**Comment by lawinslow** [comment]
Any clue how long travis will be ok with sudo:required? Is that going to be around for a long time, or are they going to start deprecating non-container based builds?

**Comment by sckott** [comment]
AFAIK, there's not going to be deprecation, but I don't know. 

Looks like Gabor's looked into using container based, but sounds like it's no faster https://github.com/metacran/r-builder/issues/20

**Comment by lawinslow** [comment]
Ok, good, just curious if there was any known plan
