### ISSUE TITLE
Creating new items requires a parent id?

### ISSUE THREAD

**Issue by sckott** [USGS-R/sbtools#103]
Are these the right docs?  https://my.usgs.gov/confluence/display/sciencebase/Creating+and+Modifying+Items#CreatingandModifyingItems-POST:CreateaNewItemdocument

If so, I would think there would be a way to create a new item that doesn't require a parent id. If true, then you have to create a folder/item in the web interface first?  

Or am I missing something?

**Comment by lawinslow** [comment]
Those are the right docs. I'm confused though, what do you mean by 

> If so, I would think there would be a way to create a new item that doesn't require a parent id. If true, then you have to create a folder/item in the web interface first?

What are you seeing that suggests you can create an item without a parent?

**Comment by sckott** [comment]
> What are you seeing that suggests you can create an item without a parent?

I'm not seeing anything, that's the issue. When I hit the `Add Item` button in the sciencebase GUI, it attached a parentid to the url. Where does that come from? e.g, i just pressed `Add Item`, and the url int he browser has `https://www.sciencebase.gov/catalog/item/editForm/new?parentId=55ddff5de4b0518e354dfceb` where does that parentid come from?

**Comment by sckott** [comment]
Oh, maybe that's the ID for me (my user account)?

**Comment by lawinslow** [comment]
Ah, ok, I was being dense. 

I think that with the online interface, it defaults to using your current location as the "parent item". So if you're in "my items", which is itself a node in the hierarchy, it uses that.

**Comment by aappling-usgs** [comment]
Yes, could be the ID for your My Folder. There's a Pick a Destination section in the GUI that let's you decide where to put it, but it probably does start with a default.

![image](https://cloud.githubusercontent.com/assets/12039957/9501849/64292f90-4bf3-11e5-9d5c-466f95aff232.png)

**Comment by sckott** [comment]
Thanks @lawinslow and @aappling-usgs 

So in this package, seems like we should have a way to get that default parentid that the GUI uses

**Comment by lawinslow** [comment]
Yeah, at least the user's "My Items" root. Not sure of service to get that info. I'll shoot the SB people an email.

**Comment by sckott** [comment]
:+1:

**Comment by lawinslow** [comment]
Moment of inspiration. Website seems to hit this URL
https://www.sciencebase.gov/catalog/folder

Which is then redirected to your my items folder. Seems to work with an authenticated session:

`GET('https://www.sciencebase.gov/catalog/folder', handle = current_session())`

Still emailing though.

**Comment by lawinslow** [comment]
There's our answer
> To find the My Items folder for a given user, you search the "Users" folder's direct children for a folder with that title.  for lwinslow@usgs.gov:
https://www.sciencebase.gov/catalog/items?parentId=4f4e4772e4b07f02db47e231&lq=title.untouched:lwinslow@usgs.gov&format=json

**Comment by sckott** [comment]
Nice find on https://github.com/USGS-R/sbtools/issues/103#issuecomment-135148204

Hmmmm, we still need to get the `parentId` in https://www.sciencebase.gov/catalog/items?parentId=4f4e4772e4b07f02db47e231&lq=title.untouched:lwinslow@usgs.gov&format=json

How do we get that?

**Comment by lawinslow** [comment]
I think the parent ID in that query doesn't change. If I understand correctly, I think it might be the master parent ID of all `My Items` children. If you do the query for your user while logged in, do you get your My Items ID?

**Comment by sckott** [comment]
i'll check...

**Comment by sckott** [comment]
using that parentid in the url above:

```r
content(query_items(list(s = "Search", parentId="4f4e4772e4b07f02db47e231", lq = "title.untouched:scott@ropensci.org", format = "json")))
```

does give back in `$items[[1]]$link$url` a URL with the same ID that I see in the browser - perfect!

Should I add a function to get this ID for an authenticated user?

**Comment by sckott** [comment]
here's a draft function

```r
user_id <- function(...) {
	args <- list(s = "Search", 
							 parentId = "4f4e4772e4b07f02db47e231", 
							 lq = paste0("title.untouched:", pkg.env$username), 
							 format = "json")
	res <- content(query_items(args, ...))
	url <- res$items[[1]]$link$url
	basename(url)
}
```
