### ISSUE TITLE
Thoughts on package interface

### ISSUE THREAD

**Issue by sckott** [USGS-R/sbtools#105]
Seems like there are a variety of different outputs from functions and variety of different inputs. But the `ID` seems to be a common input, and the `item` (or parts of an item) seem like a common output

Perhaps it makes sense to make a standard class for these things, S3 would be simplest. So, an ID could have a class, of name e.g., `sb_id`, and an item of class name e.g., `sb_item`. An `sb_id` class would just be perhaps a character string with an attached S3 class, but then you can make functions that act on that class, e.g., `id_exists()`, `as.sb_id()`. 

An item is more complicated, potentially many fields in a list. This could have an attached class, and perhaps a print method for easier viewing of the important details. Then items could be acted upon to e.g., delete the item, update it, act on a list of items appropriately, etc. 

An eg: say you're using `item_append_files()`. Whereas the example in the pkg now accepts an ID only:

```r
item_append_files("54e265a4e4b08de9379b4dfb", '/foo/bar/baz.zip')
```

You could allow either an ID or an item to be passed in, where the ID method works the same way as the fxn is now, but the `item_append_files.sb_item()` method plucks out the ID for you. And then maybe even return an item class from this function to make it easier to reason about what outputs will be.

**Comment by lawinslow** [comment]
Yeah, that sounds like a good idea. I especially like having the option to do both string and object item, making it more flexible. You're thinking two objects, an sb_id and an Item object? Maybe just merge the two? There should always be a 1:1 relationship.

**Comment by sckott** [comment]
Right, two objects. You could just have one.  I guess if you have an ID like `2349asdfasdf0898908`, then you can just coerce that into the class (whatever the class is called) e.g., like `as.sb("2349asdfasdf0898908")`, where the object just consists of the ID, and a print method would just print the ID and leave any other things that you want to print blank

**Comment by sckott** [comment]
@lawinslow should I start fleshing this out?

**Comment by lawinslow** [comment]
Yeah, I'm totally on board with this approach. Go for it!

**Comment by sckott** [comment]
:+1:

**Comment by sckott** [comment]
Here's a start on `pkgiface` branch https://github.com/sckott/sbtools/tree/pkgiface

The `sbitem` class looks like this:

```r
item_get("4f4e4b24e4b07f02db6aea14")
#> <ScienceBase Item> 
#>   Item ID:     4f4e4b24e4b07f02db6aea14
#>   Parent ID:   4f4e4771e4b07f02db47e1e4
#>   Title:       Coastal-change and glaciological maps of Antarctica
#>   Provenance (Created / Updated):  2010-10-06T04:25:43Z / 2014-07-21T17:45:42Z
#>   Children:    FALSE
```

Thoughts on this?  Other things to include in that printed object? Things to take out?  

* Demonstration of how the basic functionality works https://github.com/sckott/sbtools/blob/pkgiface/R/sb_item.R#L6-L20
* An e.g., w/ `item_get_parent()` https://github.com/sckott/sbtools/blob/pkgiface/R/item_get_parent.R#L11 - of course the pipe isn't exported from the pkg, just an example, but you could if you want :)
* Two e.g.,s w/ `item_list_children()`  https://github.com/sckott/sbtools/blob/pkgiface/R/item_list_children.R#L15-L16 

The `sbitem` class probably can't be used in some fxns, but could be used in many

**Comment by aappling-usgs** [comment]
Cool!
1) Might want to print out human-meaningful things like Title, Provenance, maybe Children before the machine-meaningful things like Item ID and Parent ID.
2) Very happy about your coersions (`as.sbitem`) in functions that accept IDs (e.g., https://github.com/sckott/sbtools/blob/pkgiface/R/item_get_parent.R#L15) - will be very useful to be able to pass in either sbitems or character strings
3) For characters, there's now very little difference between `as.sbitem` and `item_get`. Will `item_get` be deprecated / eventually internal?

**Comment by aappling-usgs** [comment]
(Just noticed y'all have already discussed (2) extensively. Consider my comment yet another thumbs up for that idea.)

**Comment by lawinslow** [comment]
Definitely agree with point 1. On point 3, I'd say leave it for backwards compatibility right now. Also has nice syntactic parallelism. Might be nice even if it's just a wrapper for `as.sbitem`

**Comment by sckott** [comment]
> Might want to print out human-meaningful things like Title, Provenance, maybe Children before the machine-meaningful things like Item ID and Parent ID.

Will do

**Comment by sckott** [comment]
@lawinslow @aappling-usgs Okay, updated the print method. 

Should i continue to integrate into other functions, fleshing our the rest of the interface

**Comment by lawinslow** [comment]
Yeah, definitely. Integrate away. I'll have some more time this week to play around with the newly integrated functions. Also going to add a testing account so we can do full POST/Delete tests on objects.

**Comment by sckott** [comment]
Great, will do

**Comment by sckott** [comment]
can we close this now given #123 merged?

**Comment by lawinslow** [comment]
Yeah!
