### ISSUE TITLE
sbtools_DELETE returns session handle

### ISSUE THREAD

**Issue by sckott** [USGS-R/sbtools#108]
Seems like this isn't the desired output?  

Perhaps return the output from the `DELETE()` call?

**Comment by lawinslow** [comment]
Good point. Maybe we could have it check the return value and give TRUE/FALSE for success/failure. Seems to be the approach other delete functions take in various programming languages.

**Comment by sckott** [comment]
Right, sometimes they return nothing to the user, but that doesn't seem very user friendly

**Comment by sckott** [comment]
should I do that?

**Comment by lawinslow** [comment]
Yeah. TRUE/FALSE is go. 

Also, just realized, I think sbtools_PUT and _DELETE should be returning `r`, the response, not an invisible session object (from `session_age_reset`). Right?

**Comment by sckott** [comment]
Yeah, I think so

**Comment by sckott** [comment]
appears to have been taken care of in 83b85528eed521cb28d49bb17bf0cdb30dd806a9

**Comment by aappling-usgs** [comment]
oops - didn't make that connection. sorry, @sckott!

**Comment by sckott** [comment]
no problem!
