### ISSUE TITLE
Feed back on disclaimer

### ISSUE THREAD

**Issue by rerickson-usgs** [USGS-R/sbtools#109]
I installed sbtools on my Windows 7 USGS computer (R version 3.2.1). The disclaimer "This information is preliminary or provisional and is subject to revision..." is much longer than one line and I had trouble scrolling through it to read it all. Perhaps you add in some line breaks. (This is a Windows R problem more than anything else. If I recall correctly, emacs ess and OS X R all have word wrap.).

**Comment by lawinslow** [comment]
That's a great point. Thanks for the note!

**Comment by lawinslow** [comment]
fixed in #110
