### ISSUE TITLE
Query interface

### ISSUE THREAD

**Issue by sckott** [USGS-R/sbtools#116]
How do you all feel about putting parameters into function definitions vs. leaving it up to the user?  

E.g., `query_items()` has the first parameter `query_list` which takes in a list of key-value pairs specifying the query. However, the user has to know what parameters are allowed and what possible values are, etc.  That's cool, but would be nice to have a man file detailing the possible parameters and what kinds of values they take, and if only a certain set of values, what the options are.   I can make this manual page if that sounds good

Another option is putting each possible parameter into the function definition, but I assume you would have done that if that's what you wanted :)

**Comment by aappling-usgs** [comment]
I think it'd be awesome to have a man file of query parameters. double :+1:

**Comment by jread-usgs** [comment]
:+1: to that!

**Comment by lawinslow** [comment]
Yeah, every possible option would probably get crazy. We could just flesh out the man file. Something not being in there already is not a sign it isn't a good idea or wanted. A lot of what's there was to move forward on other projects, not necessary complete interfaces. :-P

**Comment by sckott** [comment]
should we close given #117

**Comment by sckott** [comment]
seems sorted now, re-open if you want this open
