### ISSUE TITLE
fail nicely when user isn't logged in

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/sbtools#118]
The problem: A user tries to do something that requires authentication but hasn't called authenticate_sb(). An uninformative error is returned.

There are a lot of cases where this could happen; we've already caught some by running many calls through sbtools_PUT, sbtools_DELETE, etc., which check for authentication as needed and tell the user to log in first. But I just found another case that isn't currently covered:

```r
> library(sbtools)
> user_id()
 Error in sbtools_GET(url = pkg.env$url_items, ..., query = qury, session = session) : 
  Invalid Query 
```

There are probably others.

**Comment by aappling-usgs** [comment]
Another case: item_rm fails without a stop() on non-authentication
```r
> # fresh R session
> library(sbtools)
> item_rm("560597a5e4b058f706e514fb")
Response [https://my.usgs.gov/josso/signon/login.do?josso_back_to=https%3A%2F%2Fwww.sciencebase.gov%2Fcatalog%2Fjosso_security_check]
  Date: 2015-09-25 19:45
  Status: 405
  Content-Type: text/html;charset=utf-8
  Size: 1.12 kB

> authenticate_sb()
> item_rm("560597a5e4b058f706e514fb")
Response [https://www.sciencebase.gov/catalog/item/560597a5e4b058f706e514fb?format=json]
  Date: 2015-09-25 19:45
  Status: 200
  Content-Type: text/plain; charset=UTF-8
<EMPTY BODY>
```

In this case, `session_validate` is definitely being called, but it returns TRUE because NULL is a valid session. Maybe we need a function that tells you not just whether the session is valid but whether it implies any authority to manipulate items on SB.

**Comment by sckott** [comment]
First, it we aren't getting an informative error in the http response. We're just getting the `Invalid Query` response, and I can't find any other info in the response to help guide the user. 

Second, it looks like we can do checking within each function that we know requires authentication, and stop with error telling user to auth first. Does that seem reasonable?

**Comment by aappling-usgs** [comment]
In the case of `user_id()`, yes, I agree that checking for authentication before the call makes sense, because we should always expect a non-NULL session for that call.

In the case of item_rm(), I'm less sure. There are three possibilities:
1) The user isn't logged in at all. item_rm() should check for is.null(session) and stop if TRUE, like you suggested.
2) The user is logged in and has permission to delete the item[s]. item_rm() should send the query and exit with success.
3) The user is logged in but doesn't have permission to delete one or more of the items. I don't know what's needed here, but responses to those queries look somewhat more informative - do they give some clue about permissions-based denials?

**Comment by sckott** [comment]
sending a PR for `user_id` 

> 1) The user isn't logged in at all. item_rm() should check for is.null(session) and stop if TRUE, like you suggested.
> 2) The user is logged in and has permission to delete the item[s]. item_rm() should send the query and exit with success.
> 3) The user is logged in but doesn't have permission to delete one or more of the items. I don't know what's needed here, but responses to those queries look somewhat more informative - do they give some clue about permissions-based denials?

__1__, __2__ and __3__ are handled nicely I think already. e.g., if you aren't authenticated and you use `item_rm()` you get 

```r
Error: Item not found for ID=5679f4f8e4b0b99d4f4906fa. Either the item does not exist or the item is secured and requires authentication to access
```

Same for if you are auth'ed and you don't have access. And succeeds of course if you do have access and are auth'ed
