### ISSUE TITLE
item_exists for application to sb id

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/sbtools#119]
`item_exists` will tell you whether a tuple of identifiers specifies an existing item. But suppose I have an SB ID, say, 56059241e4b058f706e514b6, and I want to know whether it exists on SB or not. Is there already a way for me to check that? If not, could `item_exists()` be modified or could a new function be created to perform that check?

**Comment by sckott** [comment]
Looking at `item_exists()`, it doesn't look like checking an SB ID fits into that function, but maybe I'm wrong?

Thoughts on this approach: 

```r
item_id_exists = function(id, ..., session=current_session()) {
	sbtools_HEAD(url = paste0(pkg.env$url_item, id), ..., session=session)
}

sbtools_HEAD <- function(url, ..., session) {
	if (!session_validate(session))
		stop('session is not valid. See ?authenticate_sb')
	r <- HEAD(url, ..., handle=session)
	log <- if (r$status_code == 200) TRUE else FALSE
	session_age_reset()
	return(log)
}
```

```r
# Item exists
item_id_exists(id = "4f4e4b24e4b07f02db6aea14")
#> [1] TRUE

# Item does not exist
item_id_exists(id = "aaaaaaakkkkkkkbbbbbb")
#> [1] FALSE
```

However, I think most other `item_*()` functions take an SB ID as their first argument, so perhaps it makes sense to make `item_exists()` take an SB ID and perhaps use my code above, and take the current code inside `item_exists()` and give it a new fxn name?

**Comment by aappling-usgs** [comment]
A new function name for the current `item_exists()` makes sense to me.

**Comment by sckott** [comment]
sound good @lawinslow ?

**Comment by lawinslow** [comment]
Yeah, sounds good. I think the current `item_exists` could use a new name. Maybe `item_identifier_exists` or something like that? Or it could be a general `item_exists` function which takes either an sbitem, id, or scheme/type/key tuple.

**Comment by aappling-usgs** [comment]
generally in favor. since all the other `item_...` functions operate on an item, how about a name that doesn't start with `item` at all - maybe `exists_item_identifier` or `identifier_exists`?

**Comment by lawinslow** [comment]
Yeah, I like `identifier_exists`. In a way, it's a different thing.

**Comment by sckott** [comment]
should I PR?

**Comment by lawinslow** [comment]
Sure.
