### ISSUE TITLE
consolidate item_list_children and item_list_children_all

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/sbtools#120]
`item_list_children_all` was written to get the $hasChildren field for an item's children; the core `item_list_children` function only returns id and title. Seems to me the core `item_list_children` function should be able to return such information if requested; if this were true, then `item_list_children_all` could be replaced and removed.

**Comment by sckott** [comment]
Hmm, but `item_list_children_all()` is not exported, so not a user facing function. AFAICT it's only used internally in the exported function `item_rm_recursive()`

**Comment by aappling-usgs** [comment]
True. What I was suggesting is to change the functionality of `item_rm_recursive()` to do everything that `item_list_children_all()` does.

**Comment by sckott** [comment]
Hmm, not sure I have an opinion on this. Happy to make changes according to suggestions

**Comment by sckott** [comment]
@aappling-usgs hmm, now I don't think I understand what you mean here:

> change the functionality of `item_rm_recursive()` to do everything that `item_list_children_all()` does.

Just replace the code within `item_rm_recursive()` with the code within `item_list_children_all()`?

**Comment by lawinslow** [comment]
@aappling-usgs I've improved item_list_children to include a much broader array of functionality, getting close to the raw ability of `item_list_children_all` and eliminated the `_all` version. Check out the changes. If this isn't what you were thinking, re-open this issue.

**Comment by appling** [comment]
@lawinslow looks great!
