### ISSUE TITLE
folders vs items

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/sbtools#121]
I'm confused about items and folders. Can anybody explain the difference to me?

We currently have functions for item_create and folder_create; the only substantive difference I can see is that the latter includes `systemTypes = "Folder"` in the request body. When I create one of each:
```r
folder_create(user_id(), "foo")
item_create(user_id(), "bar")
```
and browse to see them in my folder in ScienceBase:
```r
httr::BROWSE(paste0("https://www.sciencebase.gov/catalog/folder/", user_id()))
```
I can see that the items have different icons, and `foo` has systemTypes set (to "Folder") where `bar` does not, but I haven't noticed other differences. 
```r
foo <- item_get(myfiles$id[myfiles$title=="foo"])
bar <- item_get(myfiles$id[myfiles$title=="bar"])
all.equal(foo$permissions, bar$permissions) # etc.
foo$systemTypes
bar$systemTypes
```
I can add files to either kind in the same way, too.

So what's the difference? How does `systemTypes="Folder"` affect the behavior of an item/folder?

**Comment by sckott** [comment]
Yeah, that's kind of weird. The two look different on creation, but yeah, you can add files to a file. I noticed when you do that, that the file then has `systemTypes` equal to `Folder`

That brings up a point, that we could perhaps DRY out our code, and use the same base helper fxn for both `item_create()` and `folder_create()`, and just add `systemTypes = "Folder"` to the latter

**Comment by sckott** [comment]
Thoughts everyone? Should anything be done about this items vs. folders question?

**Comment by aappling-usgs** [comment]
My vote is to not acknowledge folders at all in `sbtools`, just call everything an item. e.g., remove `folder_create()`, etc.

**Comment by lawinslow** [comment]
Here's my thought. If we can implement both without much code duplication, I say we do it. It's used obviously on sciencebase and first adopters of sbtools might be confused if we don't make a distinction. While there is no functional difference, there is a clarity difference.

**Comment by sckott** [comment]
Sounds good luke, I can try to use a single internal fxn for both of these, keeping both fxns exported

**Comment by lawinslow** [comment]
@sckott I went head and implemented with as much overlap as possible. Because of weird JSON boxing/non-boxing issue with SB, I couldn't move too much out of folder_create. Closing this for now.
