### ISSUE TITLE
All items gone in Sciencebase 

### ISSUE THREAD

**Issue by sckott** [USGS-R/sbtools#126]
Curious why all my items are now gone in Sciencebase?  Same for others?

**Comment by lawinslow** [comment]
Weird. Have you checked back? Sometimes they disappear while they are working on things. Everything seems ok for me on SB.

**Comment by sckott** [comment]
yep, all gone still, been 5 days now, hmmm, anyway, as long as API is still working...

**Comment by lawinslow** [comment]
Weird. You want me to contact them and track things down, or just move forward?

**Comment by sckott** [comment]
I'll work tomorrow probably on this.  Add long as api is back up all will be fine

**Comment by sckott** [comment]
api working fine
