### ISSUE TITLE
New items/folders are not showing up in my sciencebase web account

### ISSUE THREAD

**Issue by sckott** [USGS-R/sbtools#127]
hey all

when creating new items or folders, they don't show up in my scienbase account. 

It looks like all is fine using the Sciencebase API, but it's nice to be able to verify that what's happening via the API is showing up in the web interface. 

Any thoughts?  Am I the only one?

**Comment by jread-usgs** [comment]
weird. This sounds really odd to me. I am traveling right now, but would like to check on it when I am back in the office (Friday).

**Comment by sckott** [comment]
thanks @jread-usgs

**Comment by aappling-usgs** [comment]
Might have a been a temporary SB issue. I just now had success with the following:

```r
library(sbtools)
authenticate_sb()
item_create(title="himom")
item_list_children(id=user_id())
```
This gives me a list of items that includes 'himom'. When I navigate to and/or refresh the page at https://www.sciencebase.gov/catalog/folder/[output of user_id()], I see the same item appear.

I did all this right after a git pull from the USGS-R/sbtools master branch and a local rebuild this morning.

Is this the sort of thing you were trying to do, @sckott? Does it work for you today? If not, what do you see instead?

**Comment by sckott** [comment]
I can create something in the browser, then see it immediately, though creating in sbtools, it doesn't show up in the browser unless I go specifically to that URL

However, just noticed that I have four accounts somehow: 

![](https://www.dropbox.com/s/f313gi06qj3481p/Screenshot%202015-11-06%2008.13.54.png?dl=0&raw=1)

Bleh, I changed my password recently, I wonder if that created another account or something. Anyway. Can I delete the other accounts under my name?

**Comment by aappling-usgs** [comment]
Strange. Sounds like a question for sciencebase@usgs.gov.

**Comment by sckott** [comment]
emailed, thanks

**Comment by jread-usgs** [comment]
wow, that is weird. I don't think we have the same issue because we are in the myusgs directory, and your account is handled differently. Looks like SB's bug though.

**Comment by sckott** [comment]
Okay, makes more sense if my account is separate

**Comment by sckott** [comment]
this is fixed now
