### ISSUE TITLE
item_list_files and item_get should accept a full sbid

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/sbtools#130]
My old code calls `item_create` and tries to pass the result (an SB ID) into `item_list_files` and `item_get`. This worked back when item_create returned a character string, but now i have to explicitly extract the id (with `$id`) and pass THAT into `item_list_files` and `item_get` to avoid the following error. I think it makes sense for all functions that accept an ID to accept either a character string or an ID object, right? If so, these are two more functions for which that needs to happen.

Create the item (folderid, title, and actual IDs excluded but should apply to any such values):
```r
> run_id <- item_create(folderid, title=title)
> run_id
<ScienceBase Item> 
[etc]
```

The errors - both go back to `item_get`:
```r
> item_list_files(run_id)
 Error: length(url) == 1 is not TRUE 
8 stop(sprintf(ngettext(length(r), "%s is not TRUE", "%s are not all TRUE"), 
    ch), call. = FALSE, domain = NA) 
7 stopifnot(length(url) == 1) 
6 parse_url(url) 
5 handle_url(handle, url, ...) 
4 GET(url = url, ..., handle = session) at REST_helpers.R#40
3 sbtools_GET(url = paste0(pkg.env$url_item, id), ..., query = list(type = "json"), 
    session = session) at item_get.R#22
2 item_get(id, ..., session = session) at item_list_files.R#21
1 item_list_files(run_id) 
```

```r
> item_get(run_id)
 Error: length(url) == 1 is not TRUE 
7 stop(sprintf(ngettext(length(r), "%s is not TRUE", "%s are not all TRUE"), 
    ch), call. = FALSE, domain = NA) 
6 stopifnot(length(url) == 1) 
5 parse_url(url) 
4 handle_url(handle, url, ...) 
3 GET(url = url, ..., handle = session) at REST_helpers.R#40
2 sbtools_GET(url = paste0(pkg.env$url_item, id), ..., query = list(type = "json"), 
    session = session) at item_get.R#22
1 item_get(run_id) 
```

**Comment by sckott** [comment]
I can take a crack tomorrow, should I assign myself?

**Comment by aappling-usgs** [comment]
Sounds great. I won't have time in the next couple of days.

**Comment by jread-usgs** [comment]
:+1:

**Comment by sckott** [comment]
i remembered why I didn't have `item_get()` accept an object of class `sbitem` - because we use `item_get()` within the function `as.sbitem()` https://github.com/USGS-R/sbtools/blob/master/R/sb_item.R#L32 

I'll have a look at this and see if it can be fixed

**Comment by sckott** [comment]
oh, and if `item_get()` uses `as.sbitem()` within it, leads to infinite recursion problem :)

**Comment by aappling-usgs** [comment]
yeah, infinite recursion is awkward =). looks like you've already fixed it, though, where you've specified different functions for `as.sbitem.character` (which uses `item_get`) versus `as.sbitem.sbitem` (which doesn't) - right?

**Comment by sckott** [comment]
No, still broken cause if `item_get` uses `as.sbitem` then a character string id that's passed in goes to `as.sbitem.character`, wich right now calls `item_get`, which leads to recursion,

PR coming soon

**Comment by aappling-usgs** [comment]
oh, you're right

**Comment by sckott** [comment]
PR in
