### ISSUE TITLE
revisit status code checks in query_item_identifier

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/sbtools#132]
In `query_item_identifier` we currently have:
```r
# check results
if(r$status_code == 409){
	stop('Multiple items described by that ID')
}
```
I'm not sure this error makes sense in this context - `query_item_identifier` readily returns multiple items at once. Is there a way to find a list of more likely status codes & definitions for a GET query of this form, and to check for those instead?

On a related note, I'm wondering about the 'error' where you're not logged in and therefore can't get items. Is it worth warning the user when they're not logged in...every time? never? only when `length(response$items) == 0`? It should never be an error - many GET queries work fine without login - but a warning might be useful if the user intended to be logged in and has simply forgotten or let their session expire.

**Comment by sckott** [comment]
Hmm, typically APIs have in their documentation the likely errors you could get, are those anywhere.

**Comment by sckott** [comment]
@aappling-usgs seems like open a separate issue for this one

> On a related note, I'm wondering about the 'error' where you're not logged in and therefore can't get items. Is it worth warning the user when they're not logged in...every time? never? only when length(response$items) == 0? It should never be an error - many GET queries work fine without login - but a warning might be useful if the user intended to be logged in and has simply forgotten or let their session expire.

**Comment by sckott** [comment]
Can someone give egs of `query_item_identifier()` use? don't see any egs in the file

**Comment by lawinslow** [comment]
@aappling-usgs fixed this. Ironically, git blame says you wrote that status code check. I don't see the use right now, so it's been removed. 

I am unable to re-create the 'error' you are referring to when not authenticated. 

`query_item_identifier('mda_streams')` works for me no problem when authenticated nor not. If it is still an issue, re-open and elaborate.

**Comment by aappling-usgs** [comment]
I consider the `'Multiple items described by that ID'` bit fixed, though there's still the lingering question of whether there are other status codes that might come back that we could anticipate and relay usefully.

I've created a new issue (#158) to better explain the final paragraph of the first post in this issue thread.

**Comment by lawinslow** [comment]
I'm not sure if there are any other status codes. The SB documentation doesn't mention any. I'm going to punt on this until specific issues arise.

**Comment by aappling-usgs** [comment]
works for me.

On Mon, Jan 18, 2016 at 2:12 PM, Luke Winslow <notifications@github.com>
wrote:

> I'm not sure if there are any other status codes. The SB documentation
> doesn't mention any. I'm going to punt on this until specific issues arise.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-R/sbtools/issues/132#issuecomment-172641768>.
>



-- 
Alison Appling
Postdoctoral Fellow, USGS Powell Center
USGS Office of Water Information and University of Wisconsin - Madison
Phone: (608) 821-3927
