### ISSUE TITLE
Travis - use secure env vars for testing

### ISSUE THREAD

**Issue by sckott** [USGS-R/sbtools#136]
We can set secure env vars on travis, hidden keys that won't be visible in builds, etc. 

Could set one for username and one for password, then we can use `authenticate_sb()` as needed

> Would be interested in eventually testing for access to private items, but we'd need an SB account specifically for public (GitHub/Travis) tests, which sounds like a tricky nut to crack.

Would be nice to have a test account. My account is basically a test account, I don't have any important items in there that can't be deleted. So that's an option.

**Comment by sckott** [comment]
related to #133

**Comment by jread-usgs** [comment]
Have you done the secure keys for this type of thing in a pkg? It looks promising, but I didn't really know where to start.

**Comment by aappling-usgs** [comment]
Wow, didn't know this was possible! All in favor if it's as secure as it sounds.

**Comment by sckott** [comment]
docs on it http://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables

You can set them via the travis file, or just in the settings tab on the travis site for the repo - 

You access them from the travis servers using `Sys.getenv()`

AFAIK they are very secure, but i'm no travis expert.

**Comment by jread-usgs** [comment]
I looked into it for appveyor too a while ago

**Comment by aappling-usgs** [comment]
Looks like we'll want to make our tests robust to not having those variables available in some builds: 
> Encrypted environment variables are not available to pull requests from forks due to the security risk of exposing such information to unknown code.

(from webpage scott referenced above)

**Comment by jread-usgs** [comment]
We should also think about creating an SB service account a la sbtoolsdev or something like that for this purpose.

**Comment by lawinslow** [comment]
Ok, service account created and secure env vars set. sb_user and sb_pass.
