### ISSUE TITLE
query_item_identifier inconsistency?

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/sbtools#140]
paging through query results doesn't work yet. the following calls give you 664 rows of results every time, but their uniqueness varies from call to call. see:
```r
> sites=sbtools::query_item_identifier(scheme = 'mda_streams', type = 'site_root', limit = 10000, pagesize = 200); nrow(unique(sites))
[1] 659
> sites=sbtools::query_item_identifier(scheme = 'mda_streams', type = 'site_root', limit = 10000, pagesize = 200); nrow(unique(sites))
[1] 652
> sites=sbtools::query_item_identifier(scheme = 'mda_streams', type = 'site_root', limit = 10000, pagesize = 200); nrow(unique(sites))
[1] 650
> sites=sbtools::query_item_identifier(scheme = 'mda_streams', type = 'site_root', limit = 10000, pagesize = 200); nrow(unique(sites))
[1] 645
> sites=sbtools::query_item_identifier(scheme = 'mda_streams', type = 'site_root', limit = 10000, pagesize = 200); nrow(unique(sites))
[1] 652
```
all this works fine if pagesize=1000. 664 unique results every time.

**Comment by aappling-usgs** [comment]
The repeated values occur near the beginning of new pages and are repeats of values that occurred toward the end of the previous page.
![image](https://cloud.githubusercontent.com/assets/12039957/11228696/13b68f42-8d54-11e5-90a5-ab656f397932.png)
```r
sites=sbtools::query_item_identifier(scheme = 'mda_streams', type = 'site_root', limit = 10000, pagesize = 200); nrow(unique(sites))
sites$firstmatch <- match(sites$title, sites$title)
sites$rownum <- 1:nrow(sites)
library(ggplot2)
ggplot(sites, aes(x=rownum, y=firstmatch))  + geom_vline(xintercept=200*(1:3), color="palegreen") + geom_point(aes(color=(rownum == firstmatch))) + theme_bw()
```

**Comment by aappling-usgs** [comment]
left a bug report on the sciencebase site: http://feedback.sciencebase.gov/forums/73465-sciencebase/suggestions/10747197-query-results-paging-by-nextlink-yields-duplicate

**Comment by allenj** [comment]
I fix has been applied on the sciencebase side. Please re-run your tests. Thanks for the bug report.

**Comment by aappling-usgs** [comment]
Yes, it's fixed! Thanks, @allenj 
![image](https://cloud.githubusercontent.com/assets/12039957/11313591/a337b15e-8fa3-11e5-80c0-14080fbb669d.png)
(plot is from same code as above)
