### ISSUE TITLE
item_replace_files - surgical version

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/sbtools#141]
item_replace_files currently wipes out all of the item's files and then replaces them. Could we make it so it's possible to replace just one or a few of the files while leaving the others intact? Here's the current code:
```r
item_replace_files <- function(id, files, ..., session=current_session()){	
	item_rm_files(id, ..., session=session)
	item_append_files(id = id, files = files, ..., session=session)
}
```
So really, all that's needed is a way to remove just one or a handful of files at a time within `item_rm_files`.

**Comment by sckott** [comment]
not sure off the top, but I can have a look

**Comment by aappling-usgs** [comment]
that would be great, thanks. this is a blocker for a change i'd like to make in a client project.

**Comment by ldecicco-USGS** [comment]
I'd like to re-iterate that the current behavior is not (to me) expected at all. I expect that if I do this:

```
item_replace_files(x$id, "fluxBiasMulti.pdf")
```
I'm just replacing the file...not deleting allllllll my other stuff.

**Comment by lawinslow** [comment]
Ah, got it. I'll look at this next.

**Comment by lawinslow** [comment]
Argh, SB.

**Comment by lawinslow** [comment]
Ok, this functionality is now in there. item_replace_files has an `all` T/F flag. It will either remove all files and upload new ones (TRUE), or replace files with identical names as those being uploaded (FALSE). 

I'm going to close this, but please reopen if anyone has a preference for this interface change.

**Comment by appling** [comment]
Sounds like a good solution to me!

**Comment by ldecicco-USGS** [comment]
I just got bit with this again....it's my fault I know, but...could we set a default argument to all=FALSE, so you really need to mean it when you want to delete all your stuff versus just replace one file?

**Comment by appling** [comment]
I'll :+1: that preference, having worked with this function a few times since January -- `all=FALSE` would be more intuitive to me, too
