### ISSUE TITLE
Put parameters used a lot into man-roxygen templates?

### ISSUE THREAD

**Issue by sckott** [USGS-R/sbtools#145]
e.g., `...`, `session`, etc.

**Comment by jread-usgs** [comment]
I would like to do this more, but do you have an example elsewhere? I haven't been able to cook it into my package documentation workflow for common params.

**Comment by sckott** [comment]
yeah, just put a R file (e.g., `mydocs.R`) with only roxygen docs into a folder in the root named `man-roxygen` and use e.g., `@template mydocs` in a file in `R/ ` 

e.g. https://github.com/ropensci/rgbif/tree/master/man-roxygen

If you want to do this, I can start it here

**Comment by jread-usgs** [comment]
I'd like to give it a shot for starting so I can learn and use elsewhere if you are up for that.

**Comment by jread-usgs** [comment]
@sckott was looking into this. Is there an advantage to using `@template` vs `@inheritParams`? I haven't been good about reusing params elsewhere, so I am not sure what the tradeoffs are. 

also, related to this, seems we probably need consistency for `id` vs `parent_id`? 
Looking at [item_create.R](https://github.com/USGS-R/sbtools/blob/master/R/item_create.R) vs [item_upload_create.R](https://github.com/USGS-R/sbtools/blob/master/R/item_upload_create.R) which use id or parent_id for the parent_id in the POST. Should I create a separate issue for that - unless I am reading that wrong in the code?

**Comment by sckott** [comment]
`@template` vs. `@inheritParams` - depends on preference. template takes whatever you have in a R file in `man-roxygen` folder, whereas inheritparams just inherits whatever params are in another file in `R/` 

`id` in those two functions are the same I think, should make those the same, good idea to open a new issue

**Comment by lawinslow** [comment]
Ok, in addition to what @jread-usgs did, I've taken care of some stragglers.
