### ISSUE TITLE
merge param names for parent_id and id into one

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/sbtools#147]
should probably only have one sb_id param name.

**Comment by lawinslow** [comment]
It seems to me that parent_id is more clear than consolidating. In one operation, you're operating on the item itself. The other, just specifying the parent item. What's your thought with the consolidation?

**Comment by jread-usgs** [comment]
I don't think the names should differ, but I think the param details could differ between the two functions. The function takes an `sb_id` as an arg, so it should be `sb_id` or `id`. The details of what the relationship of that is to the operation would be part of the docs. That would be my suggestion.

**Comment by jread-usgs** [comment]
e.g., why is `folder_create(id,...)` and `item_upload_create(parent_id,...)` when both operate relative to a parent id?

**Comment by lawinslow** [comment]
Yeah, good point. I'd say those should both be parent_id. Settle on a common naming convention of maybe something like "parent_id" and "item_id", then parameters can be inherited and the difference between use is clear.

**Comment by lawinslow** [comment]
I'd propose changing this to "make id parameters consistent across functions" to "parent_id" and "item_id".
