### ISSUE TITLE
New user-friendly query_sb function

### ISSUE THREAD

**Issue by lawinslow** [USGS-R/sbtools#160]
Are people using the raw list output from the `query_items` function? I'm thinking about moving it internal and wrapping it with a function that returns a list of sbitem objects and does paging internally. New function might be named `query_sb`. 

Thoughts? Objections?

**Comment by aappling-usgs** [comment]
I'm using `query_items` to get parent IDs & names here: https://github.com/USGS-R/mda.streams/blob/ec7a25bd157f0edf08e86a94cbecc6c55d6f7fa2/R/get_sites.R#L41. Has `sbtools` developed to the point where there's a better solution for this problem, and/or would the new `query_sb` function make this possible/easier? Paging seems like a good idea.

**Comment by sckott** [comment]
Doesn't it return a httr `response` object right now?

**Comment by lawinslow** [comment]
@sckott Er, yeah, "raw" was not the right way to describe it. httr `response`

@aappling-usgs I'm just thinking about how to prevent the user from needing to parse the httr `response` object, and instead have a return type that is more in line with the rest of the package. `query_sb` would attempt to give you a higher-level function with more user-friendly operation.

**Comment by aappling-usgs** [comment]
As long as I can get a list of items (in whatever form) from a query, find the parentIDs of the items, and trace the parentIDs to the names of those parents, I'm good. It's only one function for me to rewrite, and I think it's great that you're working toward more user-friendly wrappers. Will `query_sb` combine the three existing functions `query_items`, `query_item_identifier`, and `query_item_in_folder`?

**Comment by lawinslow** [comment]
`query_item_identifier` has a very specific goal that may not overlap well, so I haven't quite decided there. Definitely replace `query_items` as the exposed function. Ultimately, `query_sb` might just be wrapped by some of the more specific functions.

**Comment by aappling-usgs** [comment]
OK, looking forward to whatever you come up with.

**Comment by sckott** [comment]
might want to still export `query_items()` in case users want low level access

**Comment by lawinslow** [comment]
Yeah, fair enough, doesn't hurt too much to leave it exported. I may add a bit of a "this is low-level" disclaimer to the `query_items` documentation.
