### ISSUE TITLE
Function to get WFS endpoint and read data into R from SB item

### ISSUE THREAD

**Issue by lawinslow** [USGS-R/sbtools#163]
User will be able to point this function at an SB item that has a WFS service attached and get the data loading into an SP dataframe. 

Example of an SB item with 
https://www.sciencebase.gov/catalog/item/55e372b9e4b05561fa208212

Might be able to do it with [this rOpenGov package](https://github.com/rOpenGov/rwfs), though it is not on CRAN and it follows an object inheritance model. 

Some rough code I worked out to do it using gdalUtils, which is on CRAN, but may be a pain because it relies on gdal installed externally. Worked fairly well on Windows, may have issues on other platforms. 

````
item_get_wfs = function(sb_id){
	wfs_url = item_get_wfs(sb_id)
	
	layer_info = ogrinfo(paste0('WFS:', wfs_url))
	
	#from this layer info, we need to extract layer name
	layer_raw = str_match_all(layer_info, '[[:digit:]]+: (sb:[[:alpha:]_]+) \\([Polygon|Multi Polygon]+\\)')
	
	layer_names = sapply(layer_raw, function(x)x[2])
	
	layer_names = layer_names[!is.na(layer_names) & !layer_names %in% c('sb:boundingBox', 'sb:footprint')]
	if(length(layer_names) > 1){
		stop('SB Item WFS has > 1 layer. item_download_sp currently cannot handle more than one layer')
	}
	
	fname = tempfile(fileext = '.shp')
	
	ogr2ogr(wfs_url, fname, layer_names)
	
	layer_sp <- readOGR(fname, substr(basename(fname), 1, nchar(basename(fname))-4), stringsAsFactors=FALSE)
	return(layer_sp)
	
}
````

**Comment by sckott** [comment]
> read data into R

Into what object?  a spatial object following `sp` classes?

When WFS is avail. for an item is there also other geospatial formats avail.? e.g., geojson would be easier to quickly visualize if that's a use case you're shooting for  - Thought i imagine most people are familiar with `sp` and friends

**Comment by lawinslow** [comment]
Yeah, I was thinking an object along the `sp` line. 

> When WFS is avail. for an item is there also other geospatial formats avail.? 
Well, I'm fairly certain we won't know the file format that was used to create the service itself (the raw file attached to the item), but the WFS could be used to grab JSON instead of a shapefile.

Here's a quick example
https://www.sciencebase.gov/catalogMaps/mapping/ows/55e372b9e4b05561fa208212?service=wfs&request=getFeature&version=1.0.0&outputformat=application/json&typeName=sb:Iowa_DU_Living_Lakes

The hardest part is getting out the `typeName` to grab, which can be parsed from the getCapabilities response
https://www.sciencebase.gov/catalogMaps/mapping/ows/55e372b9e4b05561fa208212?service=wfs&request=getcapabilities&version=1.0.0

Ultimately, that's what my use of ogrinfo is doing, grabbing that name. Then we could fairly easily toss together the query ourselves to grab geojson.
