### ISSUE TITLE
Function to download/load raster data? 

### ISSUE THREAD

**Issue by lawinslow** [USGS-R/sbtools#165]
This is a big question mark for me. Not sure how easy or hard it will be to generically grab and load data from OGC WCS webservices. My quick attempts today have failed. 

Data example:
https://www.sciencebase.gov/catalog/item/5065d135e4b053bff18e1ba7

Not necessarily a requirement for milestone v1.0, but I added it anyway.

**Comment by lawinslow** [comment]
There are also items with "ArcGIS REST Service" outputs like these. 
https://www.sciencebase.gov/catalog/item/54f10470e4b02419550cea54

May or may not be classified in a similar category. It's not clear to me.

**Comment by sckott** [comment]
on this issue and  #164 - Curious how many other data formats you'd want to read in? If it means having a bunch of other packages as imports that may be hard to install, then it might be worth having a separate small utilities pkg for reading data - e.g., `rgdal` is super annoying - `readr` is pretty painless though  - Right now your imports are really lightweight making this pkg easy to install :)

**Comment by lawinslow** [comment]
Yeah, excellent question. Lightweight is nice. For the more complicated gdal stuff, we could go a "suggests" route and leave it as optional functionality, leaving it otherwise light of required packages.

**Comment by sckott** [comment]
True, and check whether user has the suggested pkg, and stop with informative message if not

**Comment by lawinslow** [comment]
Yeah, exactly

**Comment by jread-usgs** [comment]
I think filetype extensions are out of scope for sbtools, mainly because part of the power of sb is its flexibility to support various filetypes. Is the idea to implement these before manuscript submission?

**Comment by lawinslow** [comment]
yeah, I'm trying to ward off the potential criticism that "this is just a package for USGS employees"

**Comment by dblodgett-usgs** [comment]
superseded by #277
