### ISSUE TITLE
Session vs. other auth?

### ISSUE THREAD

**Issue by sckott** [USGS-R/sbtools#170]
Any chance Sciencebase maintainers would consider not using session token things?  Instead use api keys/oauth. ideally keys instead of oauth. Would make auth easier in clients

**Comment by lawinslow** [comment]
Hmmm, he could ask them what their thoughts are. My guess right now is they are less concerned with the API-based clients than the human interface right now.

**Comment by sckott** [comment]
Okay, yeah, sessions seem good for browsers, but not so good for programmatic access :(

**Comment by lawinslow** [comment]
SB people said there's no planned support for near future. Can re-visit if SB support changes.
