### ISSUE TITLE
missing import or suggest

### ISSUE THREAD

**Issue by sckott** [USGS-R/sbtools#175]
seems that `sp` is not imported properly, should be in DESCRIPTION and `@import sp` or better yet `@importFrom sp <fxn1> <fxn2>`  somewhere in pkg to generate appropriate entries in NAMESPACE

**Comment by lawinslow** [comment]
@sckott think this is ok? I am hoping to keep it as optional

**Comment by sckott** [comment]
sure could be optional, but still needs to be in `Suggests` no?

**Comment by lawinslow** [comment]
Yeah, added [here](https://github.com/USGS-R/sbtools/pull/176/files#diff-35ba4a2677442e210c23a00a5601aba3R25)

**Comment by sckott** [comment]
ah okay
