### ISSUE TITLE
item_list_files returns NA when site doesn't exist

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/sbtools#18]
instead of NULL or df with nrow = 0. 

when 
```R
item_list_files(data.frame(), session = NULL)
```

**Comment by jread-usgs** [comment]
this should be handled in `item_get`

**Comment by lawinslow** [comment]
Why are you passing item_list_files a data.frame?

**Comment by jread-usgs** [comment]
oh, was actually passing it NULL. but same result.

**Comment by jread-usgs** [comment]
Any reason not to do this? 

https://github.com/jread-usgs/sbtools/commit/a462b3233096cfd6477225ff2ae32f3d424d838e

**Comment by lawinslow** [comment]
No, seems reasonable

**Comment by jread-usgs** [comment]
handled in recent PR
