### ISSUE TITLE
identifier_exists should not require login (i.e., sbtools_HEAD should use session_val?)

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/sbtools#181]
right now `identifier_exists` calls `sbtools_HEAD` calls `check_session` which breaks if `current_session()==NULL`. I think `session_val()` would be more appropriate than `check_session()` for this use case. Are there other uses of `sbtools_HEAD` that require full authentication, or can we just drop it back a notch to validity?

**Comment by aappling-usgs** [comment]
The only use of `sbtools_HEAD` that's currently in the package is in `identifier_exists`.

**Comment by lawinslow** [comment]
Good find. Seems like a valid bug with an easy fix. PR?
