### ISSUE TITLE
revisit session_check_reauth

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/sbtools#183]
This function hasn't had much attention recently, I think. I propose:

1. rename to `session_renew`
2. rewrite to check whether the session is current. if it is, re-up the session timer through a lightweight call to https://www.sciencebase.gov/catalog/status?format=json (see 5th comment in #90). if it's not current, or if the username passed in doesn't match the username of the current session, re-login using the new credentials passed as arguments to `session_renew`.
3. use `current_session()` as the default value of `session`, and move `session` to the end of the input argument list, consistent with format in `item_get`, etc.
4. continue to return NULL or the session handle, per #72 and consistent with `authenticate_sb`

Thoughts, @lawinslow @sckott @jread-usgs ?

**Comment by lawinslow** [comment]
Agreed with all points.

**Comment by aappling-usgs** [comment]
Thanks, @lawinslow . After working with this for a few minutes, I'm thinking users who intend to log in with a new username should actually be using `authenticate_sb()` instead; otherwise, `session_renew` could do something very un-renew-like (i.e., establish a totally new session). 

So as a revision to (2) above, how about only using a username, if passed in, to confirm that the old and new usernames are the same (and throwing an error otherwise)?

**Comment by jread-usgs** [comment]
:+1: I like this plan and the revision to 2.
