### ISSUE TITLE
item_rm(recursive=TRUE)

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/sbtools#186]
This seems like a bug, or I'm just reading it wrong:

```
> item_rm(phaseIkey, recursive = TRUE)
Error: Item has children. To remove children, grandchildren, etc. set recursive=TRUE.
```
I set `recursive=TRUE` so I could remove all the children, and got an error that the item has children.

**Comment by lawinslow** [comment]
I'll take a look later, probably a bug.

**Comment by lawinslow** [comment]
Hmmm, what version of `sbtools` are you using? I tried with 0.15.3 and couldn't re-create

````
> item_rm('56996f60e4b0ec051295ecc3')
Error: Item has children. To remove children, grandchildren, etc. set recursive=TRUE.
> item_rm('56996f60e4b0ec051295ecc3', recursive=TRUE)
[1] TRUE
````
