### ISSUE TITLE
query_item_in_folder returns parentless items

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/sbtools#193]
`query_item_in_folder` returns items whose parentID field is empty. as a consequence, calling `item_get_parent` on a result from `query_item_in_folder` returns NULL.
```r
> query_out <- query_item_in_folder(text="nwis_01646305", folder="5487139fe4b02acb4f0c8110", limit=5000)
> length(query_out)
[1] 25
> item_get_parent(query_out[[1]])
NULL
> query_out[[1]]
<ScienceBase Item> 
  Title: nwis_01646305
  Creator/LastUpdatedBy:      / 
  Provenance (Created / Updated):   / 
  Children: TRUE
  Item ID: 556f2978e4b0d9246a9fcfa1
  Parent ID: 
```

there are a couple of workarounds - both involve extracting the item id and calling as.sbitem on the id rather than on the original sbitem. would be nice if this were not necessary.
```r
> item_get_parent(query_out[[1]]$id)
[1] "5487139fe4b02acb4f0c8110"
> item <- as.sbitem(query_out[[1]]$id)
> item
<ScienceBase Item> 
  Title: nwis_01646305
  Creator/LastUpdatedBy:      / 
  Provenance (Created / Updated):  2015-06-03T16:21:12Z / 2015-06-17T13:54:27Z
  Children: TRUE
  Item ID: 556f2978e4b0d9246a9fcfa1
  Parent ID: 5487139fe4b02acb4f0c8110
```

solutions: 

first probably check whether `query_item_in_folder` is returning parentless items because that's what sciencebase is doing, or if it's just that sbtools is misplacing the parent when it interprets the sciencebase message. if it's on the sbtools side, fix it so the parents get stored in the items

if it's on the sciencebase side, then options include:
1. contact sciencebase and ask them to include the parentID
2. revise `query_item_in_folder` to call `as.sbitem` on all item IDs returned in a query (but this would be extremely slow)
3, revise `as.sbitem` so that if the item is already an sbitem but is missing fields, we check with sciencebase to get more information (but this would also be slow if we needed some field that WAS included already)
4.  revise `item_get_parent` to check the local item for a parent and if it's NULL, also ask sciencebase about it.

**Comment by lawinslow** [comment]
This as originally a strategic choice. When creating the sbitem list, I don't want a round-trip for every returned item. That could really negatively impact the performance of that function. Instead, I build an object around the information returned without hitting SB again. Unfortunately, by default, parentId and some other metadata were not returned. 

I've updated the `query_sb` function to, by default, request additional item metadata with the query. parentId is now included, as are a few other usual suspects. This does not include every possible field though, so if there is a specific field desired in the list of output sbitems, then it would need to be requested using the `fields` query parameter.
