### ISSUE TITLE
make query_item_identifier consistent with other queries

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/sbtools#194]
`query_item_in_folder` now wraps `query_sb`, which returns a list of `sbitems` (or an empty list). this seems to be the new convention -- `query_sb_spatial`, etc. also wrap `query_sb`. but `query_item_identifier` still follows the old convention of returning a data.frame with columns `title` and `id`. want to switch that one to return a list of sbitems as well?

`query_item_identifier`
```r
> item <- query_item_identifier(scheme='mda_streams', type='site_root', key='nwis_0723', limit=5000)
> item
data frame with 0 columns and 0 rows
> item <- query_item_identifier(scheme='mda_streams', type='site_root', key='nwis_01646305', limit=5000)
> item
          title                       id
1 nwis_01646305 556f2978e4b0d9246a9fcfa1
```

`query_item_in_folder`
```r
> query_out <- query_item_in_folder(text="nwis_0723", folder="5487139fe4b02acb4f0c8110", limit=5000)
> query_out
list()
> query_out <- query_item_in_folder(text="nwis_01646305", folder="5487139fe4b02acb4f0c8110", limit=5000)
> is.list(query_out)
[1] TRUE
> is.data.frame(query_out)
[1] FALSE
> query_out[[1]]
<ScienceBase Item> 
  Title: nwis_01646305
  Creator/LastUpdatedBy:      / 
  Provenance (Created / Updated):   / 
  Children: TRUE
  Item ID: 556f2978e4b0d9246a9fcfa1
  Parent ID: 
```

the `mda.streams` will need to watch this issue, because `mda.streams::locate_item(by='tag')` will break if and when `query_item_identifier` changes its behavior. see issue https://github.com/USGS-R/mda.streams/issues/234

**Comment by lawinslow** [comment]
> want to switch that one to return a list of sbitems as well?

Yeah, that's the ultimate goal. Those should all be switched over, though I hesitate only because I know it will break things others are doing. I guess that's why it's version 0.X.X.

**Comment by aappling-usgs** [comment]
at this point most helpful thing for my use of sbtools (and maybe others') would be a NEWS file with information on interface changes. i'm prepared to make this switch - already had to make it halfway because of the change in behavior to `query_item_in_folder` - just need to know when it happens.

**Comment by sckott** [comment]
agree, good to have a NEWS (or NEWS.md file) - I also like to paste each version's notes in releases associated with the git tag for that version, but just MHO

**Comment by aappling-usgs** [comment]
good idea! i'm gonna start doing that in other projects, too

**Comment by lawinslow** [comment]
Ok, this is now consistent in the latest version.
