### ISSUE TITLE
Error in UseMethod("as.sbitem")

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/sbtools#199]
Gah....the vocabulary of sciencebase is driving me insane (not sbtools....). But anyway, I'm logged in, and there's a page I have access to and can see that looks like this:

https://www.sciencebase.gov/catalog/item/570eaf6be4b0ef3b7ca2565e

If I also log in via `sbtools` using `authenticate_sb`, I'm seeing:

```
 is.sbitem("570eaf6be4b0ef3b7ca2565e")
[1] FALSE
```

This (I think) is the root problem that is preventing me from adding files?

```
item.id <- "570eaf6be4b0ef3b7ca2565e"
> as.sbitem(item.id)
<ScienceBase Item> 
  Title: Microplastics in 29 Great Lakes tributaries: 2014-2015
  Creator/LastUpdatedBy:     jlucido@usgs.gov / ldecicco@usgs.gov
  Provenance (Created / Updated):  2016-04-13T20:43:23Z / 2016-05-10T17:40:48Z
  Children: FALSE
  Item ID: 570eaf6be4b0ef3b7ca2565e
  Parent ID: 55a9170be4b0183d66e4667e

item_append_files(sb_id = as.sbitem(item.id), files = c("file1.csv", "file2.xlsx"))
Error in UseMethod("as.sbitem") : 
  no applicable method for 'as.sbitem' applied to an object of class "NULL"

item_append_files(sb_id = item.id, files = c("file1.csv", "file2.xlsx"))
Error in UseMethod("as.sbitem") : 
  no applicable method for 'as.sbitem' applied to an object of class "NULL"

```

So, I've tried a character string, and `as.sbitem()` that character string to tell `sbtools` where to put the files. What am I missing? I've used this function in the past, but just been stuck for awhile now.

**Comment by lawinslow** [comment]
is.sbitem doesn't it SB. It is asking if the item you are passing is a valid SB item object. (like is.numeric).  So passing it a string `is.sbitem("570eaf6be4b0ef3b7ca2565e")` will always return false. 

I don't know what's happening with `item_append_files`. Object of class NULL? Is item.id you're passing set?

**Comment by lawinslow** [comment]
Also, you may be looking for `identifier_exists`

**Comment by sckott** [comment]
@ldecicco-USGS seems that somehow the identifier you are passing when you get that error is `NULL` - since the `as.sbitem()` function has methods for character, list, and sbitem, and everything else it throws an error on

**Comment by ldecicco-USGS** [comment]
Yeah, it seems to think it is NULL, but I have no idea why it thinks it's NULL. The string ("570eaf6be4b0ef3b7ca2565e") is working for nearly all the `sbtools` functions except `item_append_files`....which is when I get this weird NULL message. I'll just add them by hand via the website. I should be able to upload different kind of files though, right? I'm trying a csv and xlsx.

**Comment by lawinslow** [comment]
What's your `sbtools` version? I can't re-produce the NULL issue.

**Comment by sckott** [comment]
note that `item_append_files()` internally calls `as.sbitem()` on the input id, so you don't need to convert it to an sbitem class first, can just pass in the string id
