### ISSUE TITLE
test for success for POST/PUT?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/sbtools#20]
see https://github.com/USGS-R/mda.streams/issues/32

**Comment by jread-usgs** [comment]
related to #73

**Comment by sckott** [comment]
What do you mean - like a unit test for the pkg, or just test that a file was successfully uploaded/updated internally in the pkg?

**Comment by lawinslow** [comment]
I think this had to do with SB failing on some calls and it wasn't clear if it was silent, or we just weren't examining the return value for success/failure. The addition of sbtools_GET and the like improves this situation. I think SB used to have more issue with this too. I haven't encountered this problem as much anymore. @jread-usgs did I do the issue justice?
