### ISSUE TITLE
authenticate_sb attempts readPassword from RGui

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/sbtools#204]
`readPassword` checks for whether .rs.askForPassword exists (i.e., whether we're in RStudio or not) before calling it as a function, but we're still getting this error when `authenticate_sb` is called from RGui:
```r
> authenticate_sb('myusername')
Error in readPassword("Please enter your Sciencebase password:") : 
  could not find function ".rs.askForPassword"
> traceback()
3: readPassword("Please enter your Sciencebase password:")
2: ifelse(missing(password), readPassword("Please enter your Sciencebase password:"), 
       password)
1: authenticate_sb("myusername")
```
I'm guessing that `readPassword` worked splendidly until we fixed the R CMD check NOTE about globally defined variables by adding this line: https://github.com/USGS-R/sbtools/blob/master/R/authenticate_sb.R#L55
```r
.rs.askForPassword <- '.global_def'
```
just above the call to `exists`:
```r
if (exists(".rs.askForPassword")) { ... }
```
I'll see what I can do.

**Comment by lawinslow** [comment]
Yeah, probably the issue. Can it be better dealt with with Hadley's answer [here](http://stackoverflow.com/a/12429344/1596891)?

**Comment by aappling-usgs** [comment]
Good idea! I'll try it.
