### ISSUE TITLE
Alter `item_list_children` to use `query_sb` internally

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/sbtools#217]
If you have more than 1000 children, this function becomes useless (unless there's a trick I'm missing). The `query_items` seems to support an offset.

**Comment by lawinslow** [comment]
No, you're probably right. `item_list_children` is limited to 1000 as it doesn't do paging. 

`query_sb` does automatic paging for you so you can exceed 1000 limit. 

`query_sb(list(parentId=user_id()), limit=2000)`

`limit` can be as as large a number as you're willing to wait for, though paging is limited to 1k blocks, so 100k items would take 100 round trips to SB.

**Comment by lawinslow** [comment]
I'm going to edit this. Really, item_list_children should just leverage `query_sb`.
