### ISSUE TITLE
Add user-agent to package?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/sbtools#218]
looks like SB has a test service to capture these strings up an running (or close to it). Patterns for this exist in dataRetrieval or geoknife.

**Comment by sckott** [comment]
this is how I do in `rgbif` https://github.com/ropensci/rgbif/blob/86cf49217fffb6df8c16c9f9b90fe137b356de4b/R/zzz.r#L293-L305 - was told that sometimes the typical user agent header is dropped, so also include a `X-USER-AGENT` header

**Comment by lawinslow** [comment]
interesting, main goal here is for tracking with SB. @jread-usgs you in contact with them? Want to check they track X-USER-AGENT as well?

**Comment by jread-usgs** [comment]
Sure, I will make contact and find out. Good idea. Thanks.
