### ISSUE TITLE
handle json parsing errors elegantly?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/sbtools#22]
`Error in parseJSON(txt) : parse error: premature EOF
                                       {"total":1,"selflink":{"rel":"s
                     (right here) ------^ `

**Comment by lawinslow** [comment]
Got an example that creates that? What function are you using?

**Comment by jread-usgs** [comment]
just `post_nwis_ts`, which runs all sites for a given nwis p_code. Eventually it gets a bad response from SB (json-wise) and fails. It is not the site or data, just funky response and the site runs fine the next time. Could catch within the function, but it probably is something that could be in `sbtools` instead. Your call.

**Comment by lawinslow** [comment]
How would you want it handled? Do you want it to re-try? I'd say it is better to fail quickly, and a reported JSON parsing error isn't the least descriptive error. Could wrap all errors in a generic SB communication error, but that could make diagnosing issues problematic in the future.

**Comment by jread-usgs** [comment]
Here is the full trace:

```
Error in parseJSON(txt) : lexical error: invalid char in json text.
          22site_root                     %7D"},"items":[<!DOCTYPE html PUBLIC "-//W3C//
                     (right here) ------^ 
9 parseJSON(txt) 
8 fromJSON_string(txt = txt, simplifyVector = simplifyVector, simplifyDataFrame = simplifyDataFrame, 
    simplifyMatrix = simplifyMatrix, flatten = flatten, ...) 
7 jsonlite::fromJSON(parse_text(x, encoding = "UTF-8"), simplifyVector = simplifyVector, 
    simplifyMatrix = simplifyMatrix, simplifyDataFrame = simplifyDataFrame, 
    ...) 
6 parser(content, ...) 
5 parse_auto(raw, type, encoding, ...) 
4 content(r, "parsed") at query_item_identifier.R#36
3 query_item_identifier(scheme = "mda_streams", type = "site_root", 
    session = session, limit = limit) at get_sites.R#22
2 get_sites() at post_nwis_ts.R#18
1 post_nwis_ts(variable = "wtr", p_code = "00010", session, startDate = "2008-01-01") 
```

**Comment by sckott** [comment]
@jread-usgs what was the call that created that error?

**Comment by jread-usgs** [comment]
Sorry, I am not sure and it is a really old post (~1 year ago), so the code is probably very different now?

**Comment by lawinslow** [comment]
I'm just going to archive and can re-open if we run into related JSON parsing issues. I think we're in better shape than we were a year ago.

**Comment by sckott** [comment]
ok
