### ISSUE TITLE
Link to paper?

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/sbtools#220]
Can you guys put the link to the paper somewhere here? Like, maybe on the readme or in the github description.

**Comment by ldecicco-USGS** [comment]
Also, probably want to put a CITATION file in inst.

**Comment by lawinslow** [comment]
Well, was just going to say I haven't done this because it hasn't gotten out of the pre-pub stage, but just checked and it's through!
https://journal.r-project.org/archive/2016-1/winslow-chamberlain-appling-etal.pdf

Of course I was notified of this....

**Comment by lawinslow** [comment]
Interesting, I thought all the R Journal articles got DOI's. But they don't.

**Comment by sckott** [comment]
> Interesting, I thought all the R Journal articles got DOI's. But they don't.

yeah, noticed that too, have asked about it, but not sure if it's on their roadmap
