### ISSUE TITLE
Empty lists returned for many spatial queries

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/sbtools#237]
All of these queries that cover the US are returning an empty list. I verified the lat/long points by plotting them on a map.

```
conus <- data.frame(
  lat = c(49.078148, 47.575022, 32.914614, 25.000481),
  long = c(-124.722111, -67.996898, -118.270335, -80.125804))


query_sb_spatial(bbox=
                   sp::SpatialPoints(conus, 
                                     proj4string = 
                                       sp::CRS("+proj=longlat +datum=NAD27")))

query_sb_spatial(long = conus$long, lat = conus$lat)

wkt_coord_str <- paste(conus$long, conus$lat, sep=" ", collapse = ",")
wkt_str <- sprintf("POLYGON((%s))", wkt_coord_str)
query_sb_spatial(bb_wkt = wkt_str)
```

Verifying points:
```
maps::map('usa')
points(conus$long, conus$lat, col="red", pch=20)
```

![image](https://user-images.githubusercontent.com/13220910/27880940-cbaae308-6194-11e7-9504-e6db37eb6c50.png)

**Comment by dblodgett-usgs** [comment]
```r
    library(sbtools)
    conus <- data.frame(
        lat = c(49.078148, 47.575022, 32.914614, 25.000481),
        long = c(-124.722111, -67.996898, -118.270335, -80.125804))


    length(query_sb_spatial(
        bbox = sp::SpatialPoints(
            conus, proj4string = sp::CRS("+proj=longlat +datum=NAD27"))))
    #> Loading required namespace: sp
    #> Warning in value[[3L]](cond): Error when calling ScienceBase, internet or server down? Original error was:
    #>  Error in curl::curl_fetch_memory(url, handle = handle): Could not resolve host: www.sciencebase.gov
    #> Warning in handle_errors(r, url, "GET", supported_types): Could not access
    #> sciencebase
    #> [1] 0

    length(query_sb_spatial(long = conus$long, lat = conus$lat))
    #> [1] 20

    length(query_sb_spatial(bb_wkt = "POLYGON((-124.722111 49.078148,-67.996898 47.575022,-79.95002274999999 27.44781217879905,-118.270335 32.914614,-124.722111 49.078148))"))
    #> [1] 20

<sup>Created on 2020-11-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

```

**Comment by lindsayplatt** [comment]
@dblodgett-usgs seems like there are two things here: 1) the `long/lat` and `bb_wkt` spatial query methods are working now, and 2) you cannot use the `bbox` method with `sp::SpatialPoints`?

**Comment by dblodgett-usgs** [comment]
That was actually a ScienceBase glitch that I missed when making the reprex.
    library(sbtools)
    conus <- data.frame(
        lat = c(49.078148, 47.575022, 32.914614, 25.000481),
        long = c(-124.722111, -67.996898, -118.270335, -80.125804))


    length(query_sb_spatial(
        bbox = sp::SpatialPoints(
            conus, proj4string = sp::CRS("+proj=longlat +datum=NAD27"))))
    #> Loading required namespace: sp
    #> [1] 20

    length(query_sb_spatial(long = conus$long, lat = conus$lat))
    #> [1] 20

    length(query_sb_spatial(bb_wkt = "POLYGON((-124.722111 49.078148,-67.996898 47.575022,-79.95002274999999 27.44781217879905,-118.270335 32.914614,-124.722111 49.078148))"))
    #> [1] 20

<sup>Created on 2020-12-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
