### ISSUE TITLE
prevent people from deleting user ids

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/sbtools#243]
So, I thought I had found a super slick way to delete all items within my account (I had nothing but stuff used to test out the sbtools distance learning lesson), but turns out I deleted my user id or something.

I ran this [DON'T DO IT] which in hindsight was not so brilliant:

```
item_rm(item_get(user_id()), recursive = TRUE)
```

Then tried to get info about my user id with no luck.
```
> is_logged_in()
[1] TRUE
> user_id()
Error in res$items[[1]] : subscript out of bounds
```

When I go to the site and click on "My Items" from the home page,

![image](https://user-images.githubusercontent.com/13220910/27961782-ef63172e-62fd-11e7-80f5-0c61b982bfeb.png)

I get a "Page Not Found" message.

![image](https://user-images.githubusercontent.com/13220910/27961806-00cb5652-62fe-11e7-8c57-bc98970553eb.png)

We should add in something to `sbtools` to prevent others from doing this.

**Comment by dblodgett-usgs** [comment]
I want to work on testing of the item manipulation functions... will add this to the list in that work.
