### ISSUE TITLE
item_get_wfs is rarely successful

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/sbtools#244]
We've struggled to find example items for which `item_get_wfs` actually returns a WFS; see https://github.com/USGS-R/training-curriculum/issues/276. Below is a summary of that exploration.

I tested 100 items, all of which had `browseType=OGC+WFS+Layer` (https://www.sciencebase.gov/catalog/items?q=&filter0=browseType=OGC+WFS+Layer)

Of the 100, only 3 returned something plottable with `item_get_wfs`. The successes were `57681584e4b07657d19f586d`, `5699855be4b0ec051295ed8b`, and `58cbe556e4b0849ce97dcd31`.

About 28 others had more than one WFS layer, which `item_get_wfs` currently can't handle. I don't see why it couldn't, if this function were prioritized for feature development.

1 item (`5851c123e4b0e2663625eb25`) lacked `sb:boundingBox` and instead had "sb:footprint", "sb:childrenBoundingBox", and "sb:children". `item_get_wfs` has no good way to deal with this.

The remaining 68 items had no layers other than `sb:boundingBox` and `sb:footprint`, which `item_get_wfs` ignores. If it's as expected that ScienceBase returns these in the `browseType=OGC+WFS+Layer` query, then maybe `item_get_wfs` should be able to handle them?

**Comment by lawinslow** [comment]
Background: `item_get_wfs` was never really a priority initially. There were few examples of its use on ScienceBase. Further, as you have found, implementation on SB itself varies. 

The bigger overarching question is, why is there no WFS/WMS library for R? With R devloping so much accessible spatial processing functionality, it's something sorely needed.

**Comment by aappling-usgs** [comment]
Understood. The existence of `item_get_wfs` does raise the question of how to deal with it now, though - if it remains a non-priority, maybe it should be deprecated until the day when a WFS/WMS library does exist? Should our [USGS packages curriculum](https://github.com/USGS-R/training-curriculum/pull/272) mention this function at all?

**Comment by lawinslow** [comment]
Depends on your perspective. I tend to take a demand-driven approach. Put it out there, see if people send feedback. It seems to be an intriguing enough feature for you guys to have gone digging into it. Maybe that's a sign it is worth more development? Definitely a judgment call.

**Comment by dblodgett-usgs** [comment]
Just dug into item_get_wfs and updated it to use sf and geojson rather than writing a shape/zip to disc. My preference would be to remove that functionality entirely to remove the dependency on sp and sf. Anyone have a preference?

**Comment by aappling-usgs** [comment]
No objection here.

**Comment by dblodgett-usgs** [comment]
I removed this in #276 as it was causing tests to fail.
