### ISSUE TITLE
Is it possible to access non-public data through url?  I have permission to access the data.

### ISSUE THREAD

**Issue by mlombard-usgs** [USGS-R/sbtools#247]
I would like to access data from a non-public item on sciencebase through the url and not have to download it.  Is this possible?  I can't seem to get it to work.    I tried accessing the url in 2 different ways, both of which work with publicly available data. 

Code with notes and output is below.  Thanks!

`library(sbtools)`
`library(data.table)`
`authenticate_sb(username = "mlombard@usgs.gov")`
`is_logged_in()`

`sb.grouppage<-item_get("5a9820c8e4b06990606ddaa3")` # the group page
`item_list_children(sb.grouppage)` #print on the screen the five children items, Arsenic Data is not public
`sb.item<-item_get("5a983f26e4b06990606ddc6b")` #this is the item_id of the non-public data file under the Arsenic Data Title
`print(sb.item)`
<ScienceBaseItem>
Title: Arsenic data
Creator/LastUpdatedBy:    mlombard@usgs.gov / mlombard@usgs.gov
Provenance:(Created / Updated):  2018-03-01T17:57:58Z / 2018-06-21T15:35:40Z
Children: FALSE
Item ID: 5a983f26e4b06990606ddc6b
Parent ID: 5a9820c8e4b06990606ddaa3

`sb.files<-item_list_files(sb.item)` # thisprints on the screen all the files associated with the non-public data
`print(sb.files)` #non-public data file named SBtestData.csv

fname size
1 SBtestData.csv 1947
url
1 https://www.sciencebase.gov/catalog/file/get/5a983f26e4b06990606ddc6b?f=__disk__3a%2Fce%2F1b%2F3ace1b8f62b2b22a35d9afce5783f51820e4d2e9

`item_file_download('5a983f26e4b06990606ddc6b', dest_dir = "F:/mlombard/Documents/R_files/")` #this works to download the file

`data<-fread("https://www.sciencebase.gov/catalog/file/get/5a983f26e4b06990606ddc6b?f=__disk__3a%2Fce%2F1b%2F3ace1b8f62b2b22a35d9afce5783f51820e4d2e9")` #gives file not found (404) error

% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0      0      0      0 --:--:--  0 --:--:-- --:--:-- --:--:--     0
Error in curl::curl_download(input, tt, mode = "wb", quiet = !showProgress) : 
HTTP error 404.

`file.oi<-sb.files[which(sb.files$fname=="SBtestData.csv"),"url"]` #This makes an object for the url address of the file of interest

`testdf<-read.csv((file.oi),stringsAsFactors=F)`#file not found error

Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
 In file(file, "rt") :
 cannot open URL 'https://www.sciencebase.gov/catalog/file/get/5a983f26e4b06990606ddc6b?f=__disk__3a%2Fce%2F1b%2F3ace1b8f62b2b22a35d9afce5783f51820e4d2e9': HTTP status was 404 # Not Found

**Comment by mlombard-usgs** [comment]
Thanks for that explanation @jread-usgs   That makes sense. 

```item file download```  is not ideal because a few different people will be accessing the data and working with it.   So in an effort to maintain version control of the data I was hoping to avoid everyone having to download the data locally in order to work with it in R.

**Comment by jread-usgs** [comment]
I see, you want to force all collaborators to read the data from SB each time and not rely on a local file (which could differ from the SB file eventually). Instead you could give them code like:
```r
get_collab_data <- function(){
   filename <- 'SBtestData.csv'
   local_file <- file.path(tempdir(), filename
   item_file_download('548b2b31e4b03f64633662a4', names=filename,
		destinations=local_file)
   data <- fread(local_file)
   unlink(local_file) 
   return(data)
}
```
and have them call `get_collab_data()`, which is the same result as your initial `fread`

**Comment by lawinslow** [comment]
@mlombard-usgs You could try using the authentication token directly and use `httr` to access the data. That would allow you to read the file directly into R, skipping the intermediate file step. Though it may complicate reading and parsing the file itself.  

Something like this should work, though I don't have a good way to test it right now. 

```R
library(sbtools)
library(data.table)
authenticate_sb(username = "mlombard@usgs.gov")
is_logged_in()

res = httr::GET("https://www.sciencebase.gov/catalog/file/get/5a983f26e4b06990606ddc6b?f=__disk__3a%2Fce%2F1b%2F3ace1b8f62b2b22a35d9afce5783f51820e4d2e9", handle=sbtools::current_session())

httr::content(res)

```
Then, you could parse the result (see `httr` documentation). CSV's and the like parse pretty easily using the `content` function. Other stuff might be harder.

**Comment by mlombard-usgs** [comment]
Thanks guys.  I tried both approaches.  Jordan - I couldn't get your function to work.   

Luke - your solution looks like it works.

**Comment by jread-usgs** [comment]
Looks like mine was missing a `)` on the end of `local_file <- file.path(tempdir(), filename`. Did it fail somewhere else? Just curious. Glad Luke's works for you :+1:

**Comment by mlombard-usgs** [comment]
The code below works.  I think I tried it once when I wasn't logged in and got a file not found error.  My bad. 

```get_collab_data <- function(){filename <- 'SBtestData.csv'
  local_file <- file.path(tempdir(), filename) 
                          item_file_download('5a983f26e4b06990606ddc6b', names=filename,destinations=local_file)
                          data <- fread(local_file)
                          unlink(local_file) 
                          return(data)}```

**Comment by dblodgett-usgs** [comment]
Going to close as fixed.
