### ISSUE TITLE
sbtools is archived on CRAN

### ISSUE THREAD

**Issue by jsta** [USGS-R/sbtools#250]
https://cran.r-project.org/web/packages/sbtools/index.html

> Package ‘sbtools’ was removed from the CRAN repository.
Formerly available versions can be obtained from the archive.
Archived on 2019-05-13 for policy violation.

**Comment by lawinslow** [comment]
@tim kern

**Comment by jsta** [comment]
I was able to pull the check fail details with the `ccheck` package:

```r 
x <- cch_pkgs(c("sbtools"))$data$check_details$output
cat(x)
```
```
Running examples in ‘sbtools-Ex.R’ failed
The error most likely occurred in:

> ### Name: item_get
> ### Title: Retrieve SB item
> ### Aliases: item_get
> 
> ### ** Examples
> 
> # Get an item
> item_get("4f4e4b24e4b07f02db6aea14")
Error: GET failed to https://www.sciencebase.gov/catalog/item/4f4e4b24e4b07f02db6aea14. check authorization and/or content
Execution halted
```

**Comment by jsta** [comment]
Maybe moving [this line](https://github.com/USGS-R/sbtools/blob/master/R/item_get.R#L15) into the `dontrun` block would solve the issue?

**Comment by dblodgett-usgs** [comment]
I switched the examples to `donttest` -- from [here](https://kbroman.org/pkg_primer/pages/tests.html)  
> Code in \dontrun{ } will never be run automatically; code in \donttest{ } will be run when a user calls example( ) but won’t be run with R CMD check. Of course, a disadvantage of \dontrun{ } and \donttest{ } is that then the code won’t be tested automatically.

PR is incoming.
