### ISSUE TITLE
sbtools not available for R v.3.6.2?

### ISSUE THREAD

**Issue by katherinejchase** [USGS-R/sbtools#254]
I get the following warning when I try to install.package "sbtools":

  package ‘sbtools’ is not available (for R version 3.6.2)

**Comment by dblodgett-usgs** [comment]
Hi @katherinejchase -- assuming you have `remotes`, can you do:
`remotes::install_github("usgs-r/sbtools")` and see if that does the trick?

I would imagine a new gran build would do the trick as well -- at the end of the day, we need to get sbtools back on CRAN though.

**Comment by katherinejchase** [comment]
Thank you for your quick response! I used the script from the USGS page and it worked:
install.packages("sbtools", repos=c("https://owi.usgs.gov/R",getOption("repos")))

**Comment by dblodgett-usgs** [comment]
Ahh. Great. Yes, since `sbtools` is not on CRAN, the basic install.packages("sbtools") will not work for now.
