### ISSUE TITLE
Remove GRAN installation instructions

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/sbtools#259]
Please remove the GRAN installation instructions as we work towards archiving the GRAN repository. Consider changing the `install_github` to use the "remotes" package (a much lighter weight package than devtools).

**Comment by jread-usgs** [comment]
@dblodgett-usgs can you take this one?

**Comment by dblodgett-usgs** [comment]
Fixed in README. Are there other places that we might have referenced GRAN of the years?
