### ISSUE TITLE
Some initial feedback

### ISSUE THREAD

**Issue by sckott** [USGS-R/sbtools#26]
* curl options - I'd suggest using `...` or similar to allow curl options to be passed 
into `GET`/`POST`/etc. 
* authentication: I haven't dug into this, but i imagine passing in the 
`session` bit to each function call makes sense more so if there are multiple
potential accounts a user could have, while if a user will only ever have
one, then perhaps the auth function could be run once by a user, and then
run internally within function calls so the user doesn't have to worry about
it

looking through this more, but these are the first two things...

**Comment by lawinslow** [comment]
@sckott, what uses do you think passing the curl options would have? Are you referring to supplying additional or different query parameters? 

Right on about authentication. It was kinda a stopgap measure to get the project rolling.

**Comment by sckott** [comment]
@lawinslow for curl options I'm talking about this stuff http://ropensci.org/blog/2014/12/18/curl-options/ - not to plug my own blog post, but just easier to point to that - basically for curl debugging, etc. - Some non-debugging usage too, like printing `progress()`, and setting a `timeout()`  so that a call fails if it hasn't succeeded within a certain time frame.

**Comment by lawinslow** [comment]
Ah, excellent point. Thanks!
