### ISSUE TITLE
does sbtools::item_replace_files() handle more than one file at a time?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/sbtools#267]
From the function name, it seems this should support multi-file uploads, but from the documentation, it doesn't:
> replaces existing files associated with an item with a new one. (Currently does not support multi-file uploads.) This function will not append an existing collection of files. If that is desired, use item_append_files

It seems to actually work for me...(I am on version 1.1.12)

**Comment by dblodgett-usgs** [comment]
I'll get this tested and fixed up in the block of work I'm queuing up.
