### ISSUE TITLE
can't destdir be the current directory by default?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/sbtools#275]
```
sbtools::item_file_download(sb_id = data_release_id, names = 'lake_metadata.csv')
Error in sbtools::item_file_download(sb_id = data_release_id, names = "lake_metadata.csv") : 
  Must have either names & destinations, or dest_dir for all files
```
seems default behavior should be that you specify the file names and those files are DL'd into your current directory.

**Comment by dblodgett-usgs** [comment]
I feel like I've always been confused by the defaults of this function. Thought there was a reason it was this way. I would up vote your suggestion.
