### ISSUE TITLE
ncdf

### ISSUE THREAD

**Issue by sckott** [USGS-R/sbtools#28]
saw mention of ncdf in the proposal and had a comment (and I don't work with ncdf formats much, so I'm kinda clueless here):

I hear from Roy Mendelssohn at NOAA that the `ncdf` package http://cran.r-project.org/web/packages/ncdf/index.html only works with older ncdf format. True?  But this pkg is nice b/c it installs on all OS'es. 

Roy said to instead use `ncdf4` http://cran.r-project.org/web/packages/ncdf4/index.html - but there are no windows binaries, and it sounds as though there never will be. 

Thoughts on this?  I ask b/c if we need `ncdf4` functionality, that could lead to a problem for windows users that aren't super savvy (aka that couldn't do install from source, etc.)

**Comment by lawinslow** [comment]
Yeah, most of the use I generally run into involves netcdf 3 standards. My opinion, we support netcdf 3 until there is cross-platform netcdf 4 support. We could think about an abstraction layer that used netcdf4 and fell back to the old package when not available (the APIs are VERY similar).

**Comment by sckott** [comment]
@lawinslow Okay, sounds good.
