### ISSUE TITLE
add a get_parent function?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/sbtools#32]
Does this fit in sbtools? 

quick way to do it is this:

```R
get_parent = function(item_id){
  
  url <- sprintf("https://www.sciencebase.gov/catalog/item/%s?format=json&fields=parentId", item_id)

  parent_id <- fromJSON(txt = url)$parentId
  
  url <- sprintf("https://www.sciencebase.gov/catalog/item/%s?format=json&fields=title", parent_id)
  parent_site <- fromJSON(txt = url)$title
  return(parent_site)
}
```
but we would ask for item json twice per id. Any better way to do this?

**Comment by jread-usgs** [comment]
and ignore the hardcoding of sciencebase.gov etc. Was just a quick way to grab parent site name

**Comment by lawinslow** [comment]
We could get the parentId without hitting the `/item/` controller, but I'm unaware of a way to get an item based on its ancestors. Basically, what you're asking is if you can query an item based on its ancestors. Quick test of what I'd think the syntax to be doesn't work, so we'd need to talk to SB people.

**Comment by jread-usgs** [comment]
How do you get parentID in that way? (w/o hitting the controller?)

**Comment by jread-usgs** [comment]
This is duplicated in #23
