### ISSUE TITLE
File Download feedback

### ISSUE THREAD

**Issue by lawinslow** [USGS-R/sbtools#34]
from @dblodgett-USGS

> would be nice if you download files function returned the paths to the files or at least the file names it downloads instead of true, but that’s minor.

We could return a list of all files downloaded with their paths, regardless of if the user supplied file names or if names were generated. This would be more useful than TRUE.

**Comment by dblodgett-usgs** [comment]
Here's an implementation that more or less does it.

https://github.com/dblodgett-usgs/hydroRsb/blob/master/R/model_file_download.R

**Comment by sckott** [comment]
I assume this applies specifically to `item_file_download()`?

**Comment by sckott** [comment]
Looking at this - curios in the REST helpers why we only support certain content types?  AFAICT `sbtools` only downloads the files, and doesn't do anything more than that like try to read the file in, etc,  -- So could we just allow any file type, esp. with GET requests?

**Comment by jread-usgs** [comment]
yeah, I had the same question here: https://github.com/USGS-R/sbtools/issues/98

Supported types vs unsupported types.

**Comment by aappling-usgs** [comment]
to summarize, i think we decided that we didn't really want to specify which types were permitted, but we needed some way to determine whether we were getting an error or not (e.g., user might not be authenticated). checking for known types was the temporary solution.

@sckott, maybe you've already fixed this today with `handle_errors` (i haven't looked very carefully...)? or maybe there's some other way to check for non-authentication & other errors?

**Comment by sckott** [comment]
Okay, thanks. Oh, so, if the `content-type` header is consistent with an authorization error, then you'd  stop on that?  

I can write some tests for `handle_errors` to make sure (ping #128 )

**Comment by aappling-usgs** [comment]
Sounds good!
