### ISSUE TITLE
check for files before remove

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/sbtools#41]
you get a 404 if the item has >0 files associated with it. Currently checks for children but not files

**Comment by jread-usgs** [comment]
Also looks like you get a 404 even if the DELETE works. The SB is doing it slightly differently, DELETE on https://www.sciencebase.gov/catalog/item/5488bf20e4b02acb4f0c92a4?format=json instead of https://www.sciencebase.gov/catalog/item/5488bf20e4b02acb4f0c92a4. Does it matter?

**Comment by aappling-usgs** [comment]
yep, just created an item, added a file, and deleted the item. no problem!
