### ISSUE TITLE
For "create" methods, need to return a fail for unauthorized

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/sbtools#47]
for example, `item_upload_create()` will return NULL if you aren't authorized to perform that action

**Comment by lawinslow** [comment]
@jread-usgs does this issue still apply? I tried this function a few different ways and got descriptive errors.
![image](https://cloud.githubusercontent.com/assets/347600/12398761/4a0adbd6-bddb-11e5-83b8-628a0e73ae85.png)

Re-open as needed.
