### ISSUE TITLE
Fix error handling when item has no files attached

### ISSUE THREAD

**Issue by lawinslow** [USGS-R/sbtools#55]
item_file_download fails cryptically, as does item_list_files

**Comment by sckott** [comment]
This currently gives an empty data.frame, `55f0b70ce4b0dacf699ead75` is an item in my account with no files in it. 

```r
item_list_files("55f0b70ce4b0dacf699ead75")
#> data frame with 0 columns and 0 rows
```

Do you want different behavior?

**Comment by lawinslow** [comment]
Ah, this may have been fixed and not closed.
