### ISSUE TITLE
Create basic user vignette

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/sbtools#58]
@mhines-usgs any interest in helping out with this?

**Comment by mhines-usgs** [comment]
@jread-usgs yes, sure

**Comment by jread-usgs** [comment]
html vignette similar to `hazardItems`?

**Comment by mhines-usgs** [comment]
@jread-usgs roger

**Comment by jread-usgs** [comment]
:+1: upvote!

**Comment by jread-usgs** [comment]
:100: :+1:

**Comment by mhines-usgs** [comment]
this is a super sad old task. i'll try to do in the next week if you are basically poking me to do that...

**Comment by jread-usgs** [comment]
@mhines-usgs we can reassign too. Just thinking that because @lawinslow is featuring this package in an upcoming R email, it would be good to have a dec readme or vignette in place

**Comment by lawinslow** [comment]
I want to get money to Scott before we go too much further. It's important to get him involved and I'd like to have discussions on API and architecture before we go about making vignettes.

**Comment by lawinslow** [comment]
I'm going to close this for now and make an additional note in the announcement that the package is in "experimental phase"

**Comment by jread-usgs** [comment]
Can you stick something in the readme?
