### ISSUE TITLE
define data query interface for generic searches

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/sbtools#60]
Use case is wanting to find public data based on spatial and/or keywords and type etc.

**Comment by jread-usgs** [comment]
using elastic search on SB end

**Comment by sckott** [comment]
What's the ScienceBase API endpoint for this?

**Comment by lawinslow** [comment]
I think it is the `/catalog/items` endpoint. Described on [sb wiki](https://my.usgs.gov/confluence/display/sciencebase/Creating+Queries+for+ScienceBase#CreatingQueriesforScienceBase-Searching)

**Comment by sckott** [comment]
thx

**Comment by sckott** [comment]
hmm, but doesn't `query_items()` already do this?

**Comment by lawinslow** [comment]
Hmm, I think it does. I'm assuming this is just old. Please reopen if I'm missing something.
