### ISSUE TITLE
support metadata entry more explicitly 

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/sbtools#63]

**Comment by sckott** [comment]
Can you give more details on this?

**Comment by lawinslow** [comment]
One of the things we don't currently have implemented is first-class functions for dealing with the [long list](https://my.usgs.gov/confluence/display/sciencebase/ScienceBase+Catalog+Item+REST+Services#ScienceBaseCatalogItemRESTServices-ItemCoreObjects) of metdata for SB items. This can all largely be accomplished with `item_update`, but it isn't super user friendly. I'm currently ok with that and would rather focus getting the MS together and seeing what reviewers say. I vote this and the other old "enhancement" issues be closed unless there are objections.
