### ISSUE TITLE
query_item_identifier fails to return an existing item

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/sbtools#65]
I think `query_item_identifier` is supplying a new, incorrect session when the `session` arg is not explicitly set. This may be because this test passes if `session` is undeclared in the args, even though the default to `session` is `current_session()`:

```
if (missing(session) || is.null(session)) {
    session = handle(pkg.env$url_base)
}
```
So there might be two problems. 1, the session gets reset to handle(pkg.env$url_base) even when you think you're choosing the default arg value. 2, the value that session gets set to is different from the value returned by current_session(). See:
```
> httr::handle(sbtools:::pkg.env$url_base)
# Host: https://www.sciencebase.gov/catalog/ <0x0000000011f31b10>
> current_session()
# Host: https://www.sciencebase.gov/catalog/ <0x0000000011cdbc00>
```

Not sure why that different session w/ same URL is tripping things up, but this turns into a problem for me in continental stream metabolism, where I created this item:
```
# find the project root ("Continental Stream Metabolism" folder)
true_sites_root <- sbtools::query_item_identifier(scheme="mda_streams", type="project_root", key="uber")$id
project_root <- sbtools::item_get_parent(true_sites_root)

# create a sandbox sites folder to work with from here on
sites_root <- sbtools::item_create(parent_id = project_root, title="Sites_dev")
sbtools::item_update_identifier(id=sites_root, scheme="mda_streams_dev", type="sites_root", key="uber") # true sites root currently has type="project_root". i find that confusing.
sites_root_saved <- sites_root
> sites_root_saved
# [1] "55568a6fe4b0a92fa7e9cf2d"
```

then i tried to find it again, but got an empty data.frame:
```
sites_root <- sbtools::query_item_identifier(scheme="mda_streams_dev", type="sites_root", key="uber")
> sites_root
# data frame with 0 columns and 0 rows
```

but if i explicitly declare session=current_session(), it works.
```
sites_root <- sbtools::query_item_identifier(scheme="mda_streams_dev", type="sites_root", key="uber", session=current_session())
> sites_root
#       title                       id
# 1 Sites_dev 55568a6fe4b0a92fa7e9cf2d
```

**Comment by lawinslow** [comment]
Yup, nice find. PR coming.
