### ISSUE TITLE
get smarter about using httr::content()

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/sbtools#73]
From httr::content: 
When using content() in a package, DO NOT use on as = "parsed". Instead, check the mime-type is what you expect, and then parse yourself. This is safer, as you will fail informatively if the API changes, and you will protect yourself against changes to httr.

See https://github.com/hadley/httr/issues/246

Currently, this is speckled throughout the package.

**Comment by jread-usgs** [comment]
handling this appropriately would allow us to drop `XML` from Imports

**Comment by sckott** [comment]
Agreed @jread-usgs on parsing like `content(result, as = "text")` then parsing separately - Also, unless we're creating XML, would you be interested in switching to `xml2` package?  It only reads xml data, but is AFAIK no slower than XML, and apparently doesn't have memory leaks, etc. like XML has.

**Comment by lawinslow** [comment]
I'm all for switching to xml2 package. Does it also eliminate the external XML library dependency on *nix?

**Comment by sckott** [comment]
Seems like `XML` is no longer imported 

Do we still want to do this, or drop this?

**Comment by lawinslow** [comment]
We can just drop it.
