### ISSUE TITLE
... applies to multiple internal GET/PUT calls in item_update_identifier

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/sbtools#78]
as I'm adding dots arguments today to pass to curl, this is the first case i've seen where the same dots have to be passed to multiple functions - in this case, within `item_update_identifier`, the dots go to both `query_item_identifier` and to `sbtools_PUT`. I'm introducing this oddity because I don't know how else to handle the dots - should we be accepting two different well-formed, single-item config lists rather than allowing the user to pass in the info in standard `curl` dots format?

**Comment by aappling-usgs** [comment]
this issue emerged in addressing #79

**Comment by lawinslow** [comment]
I'm going to close this for now. While this usage does result in some potential weird behavior, it's not first-class functionality, so I'm not that worried about breaking them out separately until we run into a clear problem. Then the nature of the problem will help direct us towards an architectural solution.
