### ISSUE TITLE
multi-file API calls

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/sbtools#88]
SB allows you to post, put, upsert, and delete multiple items at once. to my knowledge this isn't yet possible via sbtools, but boy, would it be nice! see https://my.usgs.gov/confluence/display/sciencebase/ScienceBase+Catalog+Item+REST+Services

> POST: Multiple Items
> PUT: Multiple Items
> UPSERT: Multiple Items
> DELETE: Multiple Items
> Asynchronous POST, PUT, UPSERT, and DELETE

**Comment by sckott** [comment]
Looking into this.

**Comment by sckott** [comment]
working now, PR soon

async option will take a little more work, requires getting response back then continuing to ping SB API to see if items done being created - not hard though
