### ISSUE TITLE
add files without losing tags

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/sbtools#89]
Dell says fetch the item, send the item JSON back in with the post - see Dell's pysb package for an example

**Comment by aappling-usgs** [comment]
https://my.usgs.gov/stash/projects/SBE/repos/pysb/browse

**Comment by jread-usgs** [comment]
:+1: :100:

**Comment by aappling-usgs** [comment]
see #74

**Comment by sckott** [comment]
@aappling-usgs what fxn in the python client should we look at?

**Comment by lawinslow** [comment]
I'm going to close this and continue discussion in #74 (reopen if I misunderstand and this is a separate issue)
