### ISSUE TITLE
take advantage of josso service to know whether logged in

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/sbtools#90]
this is a service you can query to tell whether you're logged in...but you need a josso ID. once you've acquired a session, you can use this service to send in the session object and see whether it's still active

**Comment by aappling-usgs** [comment]
`catalog/jossoHelper/sessionInfo?includeJossoSessionID=true&josso=xxxxxxxxx`
(but includeJossoSessionID is optional, and josso=xxxx may also be optional since that will be sent with the session info anyway)

**Comment by aappling-usgs** [comment]
you can also keep a session alive by hitting this lightweight status (or the josso helper) every 10 minutes: `catalog/status?format=json`. it returns a status number. 0 is good, 1 is warning, 2 is bad

**Comment by jread-usgs** [comment]
https://www.sciencebase.gov/catalog/jossoHelper/sessionInfo?includeJossoSessionId=true

**Comment by jread-usgs** [comment]
hitting this counts as a session refresh: https://www.sciencebase.gov/catalog/status?format=json

**Comment by sckott** [comment]
Doesn't #81 close this ?

**Comment by lawinslow** [comment]
I think the Josso service would have been a way using an additional server round-trip to verify status. Let's see how our session refresh counter works in the wild. Could always add the round trip later if we still have issues.
