### ISSUE TITLE
simplify/speed up deleting an item

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/sbtools#91]
you only have to delete child items, not child files, before you delete an item. you also probably shouldn't have to wait once you've told SB to delete the child items. we should first collect a list of SB IDs and then delete them all by ID, rather than paging through the search results, deleting one page worth, and then going to the next page of search results. 

also, you can delete multiple files at once. see my.usgs.gov/confluence/display/sciencebase/DELETE: send an array of JSON ids to catalog/items as your POST body. send an HTTP:DELETE. you can only request to delete so many at a time, though. also, one user was getting a 405 error and discovered that it helped to make sure his basic auth header was being sent in with the request.

**Comment by sckott** [comment]
@aappling-usgs What does this process look like right now using this pkg?

**Comment by aappling-usgs** [comment]
Here's an example of where I arrived this summer. I now think I'm being too cautious (e.g., in waiting for child items to delete). https://github.com/USGS-R/mda.streams/blob/master/R/delete_site.R. In this project, a site is an SB item that has several child items, each of which probably has a file attached. I headed toward a more general function here: https://github.com/USGS-R/mda.streams/blob/master/R/delete_item.R - but again, I think I've been too cautious based on Dell's comments (see next paragraph). Deletion of many items takes a long time by this method.

I created this github issue during an in-person meeting with Lei Ann and Dell of ScienceBase. Dell also referred us to his pysb python module, which you're probably familiar with: https://my.usgs.gov/stash/projects/SBE/repos/pysb/browse

If there were a simple sbtools function to delete an item and guarantee it gets deleted, children and all (or throw an error so I know it failed), I would gladly use that rather than using the whole delete_site function I linked to in the first paragraph. It would sometimes also be great to know when something has truly finished deleting in SB, so that I'd know it was OK to try adding back an item with the same name and identifiers.

**Comment by sckott** [comment]
thanks!

**Comment by sckott** [comment]
@aappling-usgs AFAI can tell, there's no way around having to delete all files within a folder/item before deleting that folder/item, correct?

**Comment by aappling-usgs** [comment]
I do think you have to delete all child items. Dell said you didn't have to delete all files, and he's the expert, but I haven't checked that statement myself.

**Comment by lawinslow** [comment]
I'm unable to delete an item with children. Perhaps there is a way to do a multi-delete where all children are listed first or something? Or maybe there's way to force it, but it isn't obvious to me. We should table and ping Dell et al.

**Comment by sckott** [comment]
@lawinslow here's draft function `item_rm_recursive()` - if interested, i can put in a PR 

```r
item_rm_recursive = function(id, ..., session=current_session()){
	ogid <- id
	while (length(id) > 0) {
		k <- lapply(id, item_list_children_all, session = session)
		todel <- unlist(lapply(k, function(z) pluck(Filter(function(x) !x$hasChildren, z), "id", "")))
		invisible(lapply(todel, file_delete, session = session))
		id <- unlist(lapply(k, function(z) pluck(Filter(function(x) x$hasChildren, z), "id", "")))
		if (length(id) > 0) {
			id <- ogid
		}
	}
	invisible(item_rm(ogid))
}

itemsurl <- function() "https://www.sciencebase.gov/catalog/items"

file_delete <- function(x, ..., session = session) {
	res <- DELETE(paste0(pkg.env$url_item, x),
								query = list(format = "json"),
								content_type_json(),
								handle = session, ...)
	if (res$status_code == 200) TRUE
}

item_list_children_all = function(id, ..., session=current_session(), limit=20) {
	query <- list('parentId'=id, 'max'=limit, 'format'='json')
	r <- sbtools_GET(url = pkg.env$url_items, ..., query=query, session=session)
	content(r, 'parsed')$items
}

pluck <- function(x, name, type) {
	if (missing(type)) {
		lapply(x, "[[", name)
	} else {
		vapply(x, "[[", name, FUN.VALUE = type)
	}
}
```

**Comment by lawinslow** [comment]
Let's see what we hear from SB team and can bring it in if needed.

**Comment by aappling-usgs** [comment]
@lawinslow - I think Dell knows & agrees that you can't delete items with children. It's files that are a different story.

@sckott - cool implementation. What do you think about passing multiple items at once to your file_delete function? Is it possible / faster? (Also a little confused about that function name - is it deleting items (as I think) or files (as it's named)? Are items & files more similar than I think?) Multi-file deletion: https://my.usgs.gov/confluence/display/sciencebase/ScienceBase+Catalog+Item+REST+Services#ScienceBaseCatalogItemRESTServices-DELETE:MultipleItems

**Comment by aappling-usgs** [comment]
Also interested in the `async` option at some point (https://my.usgs.gov/confluence/display/sciencebase/ScienceBase+Catalog+Item+REST+Services#ScienceBaseCatalogItemRESTServices-AsynchronousPOST,PUT,UPSERT,andDELETE), especially if it's faster for deleting many files.

**Comment by lawinslow** [comment]
@aappling-usgs You can delete items with files. Just closed #41 which addressed that issue. Want to test it out? 

Are you also saying it's known that items with children cannot be deleted? If so, we can bring in a recursive delete and close this issue.

**Comment by aappling-usgs** [comment]
#41 is good news - yeah, I'll give it a spin. I think I misread your earlier comment in the context of a neighboring comment in the thread, making me think you were conflating files and items this week, but sounds like you're on top of all that. Re: deleting items with children - I do think that's what Dell said, since I created this issue while sitting there with him. I thought that was also what you confirmed somewhere in this thread. All that said, it might be still worth that ping to Dell to confirm for super-duper-sure.

**Comment by lawinslow** [comment]
Already pinged the SB team. My guess is there is no "recursive delete" option as it is fairly dangerous. Supply the wrong ID and your whole file tree might be gone (much like the [classic unix horror story](http://lug.wsu.edu/node/414)), but we'll see what they say.

**Comment by sckott** [comment]
@aappling-usgs `file_delete()` is to delete just one __file__, not an __item__

`item_rm_recursive()` is to delete just one __item__, but to do so recursively through the files and folders within that item. there is a method for deleting many __items__, but that's not this

**Comment by lawinslow** [comment]
@sckott we might be able to skip file delete. I think through #111 items with files can be removed without first removing files.

**Comment by aappling-usgs** [comment]
@sckott - thanks for the clarification.

**Comment by lawinslow** [comment]
Confirmed. No built-in recursive item and child-item delete. 
> You cannot delete the parent without deleting the children.  You can delete multiple items by sending an array of ids.  You would do a DELETE at https://www.sciencebase.gov/catalog/items with the body of the request being ["id1", "id2", "id3", ... "idn"]

**Comment by sckott** [comment]
@aappling-usgs @lawinslow so where does this leave us with this issue?

**Comment by lawinslow** [comment]
I'd say lets bring the recursive function into sbtools then. There's no way to do it otherwise.

**Comment by sckott** [comment]
okay, will do

**Comment by aappling-usgs** [comment]
Reopening based on discussion with Luke -- we really would like the dangerous version of this function that deletes all child items and their children. I'm working on a PR for it right now.
