### ISSUE TITLE
DESCRIPTION file changes

### ISSUE THREAD

**Issue by sckott** [USGS-R/sbtools#92]
could use a few fixes: 

* Maybe replace `Repository` with `URL` and `BugReports` - also, repo is listed as `lawinslow/sbtools` instead of `USGS-R/sbtools`
* To make CRAN humans happy: 
    * `Title` field needs to be sentence  case
    * `Description` field likely needs to be a bit longer, including URL for sciencebase, and description of what Sciencebase is. 

I can send a PR if you want...

**Comment by lawinslow** [comment]
yeah, please do!
