### ISSUE TITLE
Examples/documentation

### ISSUE THREAD

**Issue by sckott** [USGS-R/sbtools#93]
I don't see much documentation on how to use `sbtools`

Would you be up for adding examples to the README? and/or a vignette or two?

Also, the functions themselves don't seem to have any examples. If you'd rather not do that, no worries

**Comment by lawinslow** [comment]
Both are welcome. Generally, documentation was lacking while we were writing things for specific project work, not based on a decision to exclude them.

**Comment by sckott** [comment]
Cool, will do some. Just scratching my own itch to learn how to use the pkg better
