### ISSUE TITLE
Optionally store username and password as options or env vars?

### ISSUE THREAD

**Issue by sckott** [USGS-R/sbtools#95]
For `authenticate_sb()` would you be interested in allowing retrieval of auth strings within the function?  

Could use either options (via `getOption()`) or env vars (via `Sys.getenv()`) - either in the function definition itself, e.g,. 

```r
authenticate_sb = function(username = getOption("sb_username"), password = getOption("sb_pwd")){
    ...
}
```

Or within the function e.g., 

```r
authenticate_sb = function(username, password){
    if (missing(username)) username <- getOption("sb_username") # or Sys.getenv(...)
    if (missing(password)) password <- getOption("sb_pwd") # or Sys.getenv(...)
    ....# with other logic for prompting for these strings if not stored and not given in function call
}
```

**Comment by lawinslow** [comment]
Eh, I'm hoping to prevent any plain-text storage of passwords where possible.

**Comment by sckott** [comment]
> plain-text storage of passwords

What do you mean?  You mean prevent users from storing them on their machine? Or prevent from storing in the R session?

**Comment by lawinslow** [comment]
Both. I'm a little uncomfortable with the ability to pass the password into a function, which could leave it around in R history. But I think we should leave that for now.

**Comment by sckott** [comment]
okay, makes sense

feel free to close
