### ISSUE TITLE
Error in sbtools_GET

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/sbtools#98]
https://github.com/USGS-R/sbtools/blob/master/R/REST_helpers.R#L39

does not support the type I would like to get, which is:

"text/csv"

**Comment by lawinslow** [comment]
Do you have an example item I can test against?

**Comment by ldecicco-USGS** [comment]
```r
rawDataID <- "55dcd1e2e4b0518e354d4a18"

tempFolder <- tempdir()

item_file_download(rawDataID, names='bootOut.csv',
                   destinations = file.path(tempFolder,'bootOut.csv'), 
                   overwrite_file=TRUE)

bootOut <- read.csv(file.path(tempFolder,'bootOut.csv'))
```
Let me know if you can/can't see it

**Comment by jread-usgs** [comment]
works with my branch fix @ldecicco-USGS, but it is a cheesy solution and we should handle this differently. I forget were our convo ended, but `unsupported` types would be more robust than `supported` types. I think there was a different way to check that we were ending up returning login content, but I can't remember.

**Comment by lawinslow** [comment]
@ldecicco-USGS want to close when you confirm #99 fixes this?

**Comment by ldecicco-USGS** [comment]
Thanks all
